import { SuperAdminUser } from '@/types/auth';
import { Product, Category } from '@/types/product';
import { Supplier } from '@/types/supplier';
import { PaymentMethod } from '@/types/paymentMethod';
import { Customer } from '@/types/customer';
import { Order } from '@/types/order';
import { Vehicle } from '@/types/vehicle';
import { Driver } from '@/types/driver';
import { Trip } from '@/types/trip';
import { RevenueMetrics, Transaction } from '@/types/finance';
import { SalesByCity, SalesByCategory, OperationalPerformance } from '@/types/report';
import { Notification } from '@/types/notification';
import { AdminUser, AuditLog, ActiveSession, SecurityAlert, IpBlockRule, FailedLoginLog } from '@/types/security';
import { CityConfig, PlatformSettings } from '@/types/settings';
import { SupportTicket } from '@/types/support';
import { SystemService, MaintenanceWindow, MaintenanceTask, EquipmentServiceLog } from '@/types/maintenance';
import { FeedbackItem, FeedbackMetrics } from '@/types/feedback';

// Current Super Admin
export const mockSuperAdmin: SuperAdminUser = {
  id: 'ADM-001',
  name: 'Abebe Kebede',
  email: 'admin@ardabmarket.com',
  role: 'SUPER_ADMIN',
  avatar: 'AK',
  phone: '+251 91 123 4567',
  lastLogin: 'Today at 09:15 AM',
  createdAt: '2025-01-10',
};

// Current Sub Admin
export const mockSubAdmin: SuperAdminUser = {
  id: 'ADM-SUB-001',
  name: 'Eden Tilahun',
  email: 'subadmin@ardabmarket.com',
  role: 'SUB_ADMIN',
  avatar: 'ET',
  phone: '+251 92 887 6543',
  lastLogin: 'Today at 10:30 AM',
  createdAt: '2025-01-20',
};

// Categories
export const mockCategories: Category[] = [
  {
    id: 'CAT-01',
    name: 'Grains & Cereals',
    slug: 'grains-cereals',
    icon: 'bi-flower1',
    description: 'Prime Magna Teff, Barley, Wheat, Sorghum directly sourced from high plateaus',
    productCount: 24,
    status: 'ACTIVE',
    createdAt: '2025-01-12',
  },
  {
    id: 'CAT-02',
    name: 'Coffee & Spices',
    slug: 'coffee-spices',
    icon: 'bi-cup-hot',
    description: 'Premium Yirgacheffe, Sidama beans, Berbere, Korarima, Shiro blends',
    productCount: 18,
    status: 'ACTIVE',
    createdAt: '2025-01-12',
  },
  {
    id: 'CAT-03',
    name: 'Honey & Natural Sweeteners',
    slug: 'honey-sweeteners',
    icon: 'bi-droplet-fill',
    description: 'Pure White Tigray Honey, Forest Honey, and Yellow Honey',
    productCount: 9,
    status: 'ACTIVE',
    createdAt: '2025-01-15',
  },
  {
    id: 'CAT-04',
    name: 'Edible Oils & Seeds',
    slug: 'edible-oils',
    icon: 'bi-shield-check',
    description: 'Cold-pressed Niger seed (Nug) oil, Sesame, Linseed, Sunflower oils',
    productCount: 12,
    status: 'ACTIVE',
    createdAt: '2025-01-18',
  },
  {
    id: 'CAT-05',
    name: 'Pulses & Legumes',
    slug: 'pulses-legumes',
    icon: 'bi-basket3',
    description: 'Red lentils (Misir), Chickpeas (Shimbra), Horse beans (Bakela)',
    productCount: 15,
    status: 'ACTIVE',
    createdAt: '2025-01-20',
  },
  {
    id: 'CAT-06',
    name: 'Fresh Dairy & Butter',
    slug: 'dairy-butter',
    icon: 'bi-egg-fried',
    description: 'Cultured Spiced Ethiopian Clarified Butter (Kibe), Ayib, Yogurt',
    productCount: 8,
    status: 'ACTIVE',
    createdAt: '2025-02-01',
  },
];

// Payment Methods
export const mockPaymentMethods: PaymentMethod[] = [
  {
    id: 'pm-cbe-01',
    name: 'Commercial Bank of Ethiopia (CBE)',
    provider: 'BANK_TRANSFER',
    accountName: 'Ardab Market Settlement',
    description: 'Main Ethiopian commercial settlement channel',
    isActive: true,
  },
  {
    id: 'pm-dashen-02',
    name: 'Dashen Bank / Amole',
    provider: 'BANK_TRANSFER',
    accountName: 'Ardab Market Agro Settlements',
    description: 'Direct settlement via Dashen Amole network',
    isActive: true,
  },
  {
    id: 'pm-awash-03',
    name: 'Awash Bank',
    provider: 'BANK_TRANSFER',
    accountName: 'Ardab Operations Escrow',
    description: 'Awash commercial settlement account',
    isActive: true,
  },
  {
    id: 'pm-telebirr-04',
    name: 'Telebirr SuperApp',
    provider: 'TELEBIRR',
    accountName: 'Ardab Market Enterprise Merchant',
    description: 'Ethio Telecom mobile money merchant gateway',
    isActive: true,
  },
  {
    id: 'pm-cbe-birr-05',
    name: 'CBE Birr',
    provider: 'CBE_BIRR',
    accountName: 'Ardab Market Cooperative Escrow',
    description: 'CBE Birr mobile banking settlement gateway',
    isActive: true,
  },
];

// Suppliers
export const mockSuppliers: Supplier[] = [
  {
    id: 'SUP-001',
    name: 'Girma Wube',
    companyName: 'Gondar Farmers Union Cooperative',
    phone: '+251 91 876 1122',
    email: 'gondar.farmers@example.et',
    city: 'Gondar',
    category: 'Grains & Teff',
    tinNumber: '0048192019',
    address: 'Arada Commercial Zone, Near Old Silo, Gondar',
    status: 'ACTIVE',
    productCount: 14,
    registeredAt: '2025-01-10',
    paymentMethods: [
      {
        id: 'spm-01',
        paymentMethod: 'Commercial Bank of Ethiopia (CBE)',
        accountNumber: '1000293848123',
        isPrimary: true,
      },
      {
        id: 'spm-02',
        paymentMethod: 'Telebirr',
        accountNumber: '0918761122',
        isPrimary: false,
      },
    ],
  },
  {
    id: 'SUP-002',
    name: 'Selamawit Dagne',
    companyName: 'Lake Tana Agro Industries PLC',
    phone: '+251 91 582 3344',
    email: 'contact@laketanaagro.et',
    city: 'Bahir Dar',
    category: 'Edible Oils & Seeds',
    tinNumber: '0092817462',
    address: 'Industrial Development Zone, Kebele 14, Bahir Dar',
    status: 'ACTIVE',
    productCount: 8,
    registeredAt: '2025-01-15',
    paymentMethods: [
      {
        id: 'spm-03',
        paymentMethod: 'Dashen Bank / Amole',
        accountNumber: '500291823901',
        isPrimary: true,
      },
    ],
  },
  {
    id: 'SUP-003',
    name: 'Dawit Yohannes',
    companyName: 'Abyssinia Specialty Roasters',
    phone: '+251 91 144 5566',
    email: 'trade@abyssiniacoffee.et',
    city: 'Addis Ababa',
    category: 'Coffee & Spices',
    tinNumber: '0019283746',
    address: 'Bole Sub-City, Woreda 03, Industrial Park, Addis Ababa',
    status: 'ACTIVE',
    productCount: 6,
    registeredAt: '2025-01-20',
    paymentMethods: [
      {
        id: 'spm-04',
        paymentMethod: 'Awash Bank',
        accountNumber: '0132049182012',
        isPrimary: true,
      },
      {
        id: 'spm-05',
        paymentMethod: 'Commercial Bank of Ethiopia (CBE)',
        accountNumber: '1000445566778',
        isPrimary: false,
      },
    ],
  },
  {
    id: 'SUP-004',
    name: 'Berhanu Melaku',
    companyName: 'Simien Highlands Honey & Dairy',
    phone: '+251 92 344 7788',
    email: 'simienhoney@example.et',
    city: 'Gondar',
    category: 'Honey & Natural Sweeteners',
    tinNumber: '0066129843',
    address: 'Azezo Road, Agro Park #4, Gondar',
    status: 'ACTIVE',
    productCount: 5,
    registeredAt: '2025-02-01',
    paymentMethods: [
      {
        id: 'spm-06',
        paymentMethod: 'Commercial Bank of Ethiopia (CBE)',
        accountNumber: '1000882716253',
        isPrimary: true,
      },
    ],
  },
  {
    id: 'SUP-005',
    name: 'Aster Kebede',
    companyName: 'Gojjam Pulses & Legumes Millers',
    phone: '+251 93 455 8899',
    email: 'gojjampulses@example.et',
    city: 'Bahir Dar',
    category: 'Pulses & Legumes',
    tinNumber: '0077382910',
    address: 'Shimbit Logistics Hub, Bahir Dar',
    status: 'ACTIVE',
    productCount: 9,
    registeredAt: '2025-02-10',
    paymentMethods: [
      {
        id: 'spm-07',
        paymentMethod: 'CBE Birr',
        accountNumber: '0934558899',
        isPrimary: true,
      },
    ],
  },
];

// Products
export const mockProducts: Product[] = [
  {
    id: 'PRD-101',
    name: 'Magna White Teff (50 KG Bag)',
    sku: 'TEF-MGN-50',
    category: 'Grains & Cereals',
    categoryId: 'CAT-01',
    sellerId: 'SUP-001',
    sellerName: 'Gondar Farmers Union Cooperative',
    description: 'Grade-A pure Magna white teff from Gojjam, thoroughly sifted and stone-free.',
    sellingPrice: 5510,
    originalPrice: 5800,
    discountPercent: 5,
    discountPrice: 5510,
    weightKg: 50,
    unit: 'bag',
    availability: 'IN_STOCK',
    cityAvailability: ['Gondar', 'Bahir Dar', 'Addis Ababa'],
    status: 'ACTIVE',
    createdAt: '2025-02-01',
    updatedAt: '2025-03-01',
  },
  {
    id: 'PRD-102',
    name: 'Sergegna Mixed Teff (50 KG Bag)',
    sku: 'TEF-SRG-50',
    category: 'Grains & Cereals',
    categoryId: 'CAT-01',
    sellerId: 'SUP-001',
    sellerName: 'Gondar Farmers Union Cooperative',
    description: 'High-nutrient balanced brown and white teff blend, freshly bagged.',
    sellingPrice: 4950,
    originalPrice: 4950,
    discountPercent: 0,
    weightKg: 50,
    unit: 'bag',
    availability: 'IN_STOCK',
    cityAvailability: ['Gondar', 'Bahir Dar', 'Addis Ababa'],
    status: 'ACTIVE',
    createdAt: '2025-02-02',
    updatedAt: '2025-03-02',
  },
  {
    id: 'PRD-103',
    name: 'Yirgacheffe Specialty Washed Coffee (10 KG)',
    sku: 'COF-YRG-10',
    category: 'Coffee & Spices',
    categoryId: 'CAT-02',
    sellerId: 'SUP-003',
    sellerName: 'Abyssinia Specialty Roasters',
    description: 'Single-origin washed floral notes, jasmine aroma, medium roast grade 1.',
    sellingPrice: 3060,
    originalPrice: 3400,
    discountPercent: 10,
    discountPrice: 3060,
    weightKg: 10,
    unit: 'pack',
    availability: 'IN_STOCK',
    cityAvailability: ['Addis Ababa', 'Bahir Dar'],
    status: 'ACTIVE',
    createdAt: '2025-02-05',
    updatedAt: '2025-03-04',
  },
  {
    id: 'PRD-104',
    name: 'Special Traditional Berbere Spice Mix (15 KG)',
    sku: 'SPC-BRB-15',
    category: 'Coffee & Spices',
    categoryId: 'CAT-02',
    sellerId: 'SUP-003',
    sellerName: 'Abyssinia Specialty Roasters',
    description: 'Authentic 16-spice infused dried red pepper sun-dried and ground to perfection.',
    sellingPrice: 4200,
    originalPrice: 4200,
    discountPercent: 0,
    weightKg: 15,
    unit: 'bucket',
    availability: 'IN_STOCK',
    cityAvailability: ['Gondar', 'Bahir Dar', 'Addis Ababa'],
    status: 'ACTIVE',
    createdAt: '2025-02-08',
    updatedAt: '2025-03-05',
  },
  {
    id: 'PRD-105',
    name: 'Pure White Highlands Honey (25 KG Bucket)',
    sku: 'HNY-WHT-25',
    category: 'Honey & Natural Sweeteners',
    categoryId: 'CAT-03',
    sellerId: 'SUP-004',
    sellerName: 'Simien Highlands Honey & Dairy',
    description: 'Raw cold-harvested white honey from high altitude flora, rich texture.',
    sellingPrice: 7650,
    originalPrice: 8500,
    discountPercent: 10,
    discountPrice: 7650,
    weightKg: 25,
    unit: 'bucket',
    availability: 'IN_STOCK',
    cityAvailability: ['Gondar', 'Bahir Dar', 'Addis Ababa'],
    status: 'ACTIVE',
    createdAt: '2025-02-10',
    updatedAt: '2025-03-06',
  },
  {
    id: 'PRD-106',
    name: 'Refined Nug (Niger Seed) Cooking Oil (20L Jerrycan)',
    sku: 'OIL-NUG-20',
    category: 'Edible Oils & Seeds',
    categoryId: 'CAT-04',
    sellerId: 'SUP-002',
    sellerName: 'Lake Tana Agro Industries PLC',
    description: 'Pure cold-pressed domestic Niger seed oil, high smoke point, 100% natural.',
    sellingPrice: 4370,
    originalPrice: 4600,
    discountPercent: 5,
    discountPrice: 4370,
    weightKg: 19,
    unit: 'jerrycan',
    availability: 'IN_STOCK',
    cityAvailability: ['Gondar', 'Bahir Dar', 'Addis Ababa'],
    status: 'ACTIVE',
    createdAt: '2025-02-12',
    updatedAt: '2025-03-07',
  },
  {
    id: 'PRD-107',
    name: 'Highland Red Split Lentils - Misir (25 KG)',
    sku: 'PLS-MSR-25',
    category: 'Pulses & Legumes',
    categoryId: 'CAT-05',
    sellerId: 'SUP-005',
    sellerName: 'Gojjam Pulses & Legumes Millers',
    description: 'Polished split red lentils, fast cooking, exceptional taste and protein.',
    sellingPrice: 3800,
    originalPrice: 3800,
    discountPercent: 0,
    weightKg: 25,
    unit: 'bag',
    availability: 'IN_STOCK',
    cityAvailability: ['Gondar', 'Bahir Dar'],
    status: 'ACTIVE',
    createdAt: '2025-02-15',
    updatedAt: '2025-03-08',
  },
  {
    id: 'PRD-108',
    name: 'Traditional Spiced Clarified Butter - Kibe (10 KG)',
    sku: 'DRY-KIB-10',
    category: 'Fresh Dairy & Butter',
    categoryId: 'CAT-06',
    sellerId: 'SUP-004',
    sellerName: 'Simien Highlands Honey & Dairy',
    description: 'Rich pasture butter simmered with koseret, tikur azmud, and turmeric.',
    sellingPrice: 5580,
    originalPrice: 6200,
    discountPercent: 10,
    discountPrice: 5580,
    weightKg: 10,
    unit: 'tin',
    availability: 'LIMITED',
    cityAvailability: ['Gondar', 'Addis Ababa'],
    status: 'ACTIVE',
    createdAt: '2025-02-18',
    updatedAt: '2025-03-09',
  },
];

// Customers
export const mockCustomers: Customer[] = [
  {
    id: 'CUST-001',
    name: 'Almaz Tadesse',
    phone: '+251 91 144 8821',
    email: 'almaz.t@example.com',
    city: 'Gondar',
    deliveryZone: 'Arada Central',
    address: 'Near Fasil Ghebbi, House #204',
    accountStatus: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    orderCount: 18,
    totalSpendingEtb: 142500,
    trustScore: 98,
    registeredAt: '2025-01-14',
    lastOrderAt: 'Today at 08:30 AM',
  },
  {
    id: 'CUST-002',
    name: 'Solomon Mengistu',
    phone: '+251 92 334 1109',
    email: 'solomon.m@example.com',
    city: 'Bahir Dar',
    deliveryZone: 'Kebele 04 Lakefront',
    address: 'Bole Road, Near Palm Palace Hotel',
    accountStatus: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    orderCount: 12,
    totalSpendingEtb: 98400,
    trustScore: 95,
    registeredAt: '2025-01-20',
    lastOrderAt: 'Yesterday',
  },
  {
    id: 'CUST-003',
    name: 'Hiwot Assefa',
    phone: '+251 91 889 0012',
    email: 'hiwot.a@example.com',
    city: 'Addis Ababa',
    deliveryZone: 'Bole Commercial Hub',
    address: 'Atlas Area, House 450, Bole Sub-City',
    accountStatus: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    orderCount: 24,
    totalSpendingEtb: 215000,
    trustScore: 100,
    registeredAt: '2025-01-10',
    lastOrderAt: 'Today at 10:15 AM',
  },
  {
    id: 'CUST-004',
    name: 'Kassahun Bekele',
    phone: '+251 93 456 7890',
    email: 'kassahun.b@example.com',
    city: 'Gondar',
    deliveryZone: 'Maraki Campus Zone',
    address: 'University Main Gate, Commercial Row #12',
    accountStatus: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    orderCount: 8,
    totalSpendingEtb: 64200,
    trustScore: 90,
    registeredAt: '2025-02-02',
    lastOrderAt: '3 days ago',
  },
  {
    id: 'CUST-005',
    name: 'Birtukan Lemma',
    phone: '+251 94 512 3456',
    email: 'birtukan.l@example.com',
    city: 'Bahir Dar',
    deliveryZone: 'Shimbit District',
    address: 'Opposite Tana Secondary School',
    accountStatus: 'ACTIVE',
    verificationStatus: 'VERIFIED',
    orderCount: 5,
    totalSpendingEtb: 39500,
    trustScore: 88,
    registeredAt: '2025-02-11',
    lastOrderAt: '5 days ago',
  },
  {
    id: 'CUST-006',
    name: 'Yonas Gebre',
    phone: '+251 95 678 9012',
    email: 'yonas.g@example.com',
    city: 'Addis Ababa',
    deliveryZone: 'Yeka CMC',
    address: 'CMC Michael Commercial Center #30',
    accountStatus: 'SUSPENDED',
    verificationStatus: 'UNVERIFIED',
    orderCount: 1,
    totalSpendingEtb: 5800,
    trustScore: 40,
    registeredAt: '2025-02-28',
    lastOrderAt: '12 days ago',
  },
];

// Vehicles - Capacity strictly 5,000 KG per trip
export const mockVehicles: Vehicle[] = [
  {
    id: 'ARD-001',
    registrationNumber: 'ET-3-A4928',
    model: 'Isuzu NPR 5.0T Cargo',
    city: 'Gondar',
    capacityKg: 5000,
    currentLoadKg: 4350,
    remainingCapacityKg: 650,
    utilizationPercentage: 87,
    status: 'ON_TRIP',
    assignedDriverId: 'DRV-101',
    assignedDriverName: 'Bekele Tessema',
    currentTripId: 'TRP-1042',
    currentLocation: 'Arada Central -> Maraki Corridor',
    lastMaintenanceDate: '2025-02-20',
    nextMaintenanceDate: '2025-04-20',
    fuelLevelPercentage: 82,
  },
  {
    id: 'ARD-002',
    registrationNumber: 'ET-3-A5012',
    model: 'Isuzu NPR 5.0T Cargo',
    city: 'Gondar',
    capacityKg: 5000,
    currentLoadKg: 4800,
    remainingCapacityKg: 200,
    utilizationPercentage: 96,
    status: 'LOADING',
    assignedDriverId: 'DRV-102',
    assignedDriverName: 'Dawit Haile',
    currentTripId: 'TRP-1043',
    currentLocation: 'Gondar Central Logistics Hub',
    lastMaintenanceDate: '2025-02-15',
    nextMaintenanceDate: '2025-04-15',
    fuelLevelPercentage: 95,
  },
  {
    id: 'ARD-003',
    registrationNumber: 'ET-3-B2109',
    model: 'Isuzu Forward 5.0T',
    city: 'Bahir Dar',
    capacityKg: 5000,
    currentLoadKg: 3950,
    remainingCapacityKg: 1050,
    utilizationPercentage: 79,
    status: 'ON_TRIP',
    assignedDriverId: 'DRV-103',
    assignedDriverName: 'Girma Wolde',
    currentTripId: 'TRP-1044',
    currentLocation: 'Kebele 04 -> Shimbit',
    lastMaintenanceDate: '2025-02-25',
    nextMaintenanceDate: '2025-04-25',
    fuelLevelPercentage: 74,
  },
  {
    id: 'ARD-004',
    registrationNumber: 'ET-3-B2115',
    model: 'Isuzu NPR 5.0T Cargo',
    city: 'Bahir Dar',
    capacityKg: 5000,
    currentLoadKg: 0,
    remainingCapacityKg: 5000,
    utilizationPercentage: 0,
    status: 'AVAILABLE',
    assignedDriverId: 'DRV-104',
    assignedDriverName: 'Mulugeta Zewde',
    currentLocation: 'Bahir Dar Depot Station',
    lastMaintenanceDate: '2025-03-01',
    nextMaintenanceDate: '2025-05-01',
    fuelLevelPercentage: 100,
  },
  {
    id: 'ARD-005',
    registrationNumber: 'ET-3-C8814',
    model: 'Mitsubishi Fuso 5.0T',
    city: 'Addis Ababa',
    capacityKg: 5000,
    currentLoadKg: 4600,
    remainingCapacityKg: 400,
    utilizationPercentage: 92,
    status: 'ON_TRIP',
    assignedDriverId: 'DRV-105',
    assignedDriverName: 'Tadesse Alemu',
    currentTripId: 'TRP-1045',
    currentLocation: 'Bole Ring Road Southbound',
    lastMaintenanceDate: '2025-02-28',
    nextMaintenanceDate: '2025-04-28',
    fuelLevelPercentage: 68,
  },
  {
    id: 'ARD-006',
    registrationNumber: 'ET-3-C8820',
    model: 'Isuzu NPR 5.0T Cargo',
    city: 'Addis Ababa',
    capacityKg: 5000,
    currentLoadKg: 0,
    remainingCapacityKg: 5000,
    utilizationPercentage: 0,
    status: 'MAINTENANCE',
    assignedDriverId: undefined,
    currentLocation: 'Addis Ababa Fleet Workshop, Kaliti',
    lastMaintenanceDate: '2025-03-10',
    nextMaintenanceDate: '2025-03-15',
    fuelLevelPercentage: 45,
  },
];

// Drivers - Ardab internal staff
export const mockDrivers: Driver[] = [
  {
    id: 'DRV-101',
    name: 'Bekele Tessema',
    phone: '+251 91 190 4432',
    email: 'bekele.t@ardablogistics.et',
    city: 'Gondar',
    licenseNumber: 'ETH-GD-99382',
    status: 'ON_TRIP',
    assignedVehicleId: 'ARD-001',
    assignedVehicleReg: 'ET-3-A4928',
    currentTripId: 'TRP-1042',
    activeDeliveriesCount: 12,
    completedDeliveriesCount: 438,
    rating: 4.95,
    onTimeDeliveryRate: 98.8,
    joinedDate: '2024-06-15',
  },
  {
    id: 'DRV-102',
    name: 'Dawit Haile',
    phone: '+251 92 233 8812',
    email: 'dawit.h@ardablogistics.et',
    city: 'Gondar',
    licenseNumber: 'ETH-GD-88124',
    status: 'ACTIVE',
    assignedVehicleId: 'ARD-002',
    assignedVehicleReg: 'ET-3-A5012',
    currentTripId: 'TRP-1043',
    activeDeliveriesCount: 14,
    completedDeliveriesCount: 392,
    rating: 4.88,
    onTimeDeliveryRate: 97.5,
    joinedDate: '2024-07-01',
  },
  {
    id: 'DRV-103',
    name: 'Girma Wolde',
    phone: '+251 91 876 5432',
    email: 'girma.w@ardablogistics.et',
    city: 'Bahir Dar',
    licenseNumber: 'ETH-BD-55198',
    status: 'ON_TRIP',
    assignedVehicleId: 'ARD-003',
    assignedVehicleReg: 'ET-3-B2109',
    currentTripId: 'TRP-1044',
    activeDeliveriesCount: 11,
    completedDeliveriesCount: 512,
    rating: 4.92,
    onTimeDeliveryRate: 99.1,
    joinedDate: '2024-04-10',
  },
  {
    id: 'DRV-104',
    name: 'Mulugeta Zewde',
    phone: '+251 93 331 4455',
    email: 'mulugeta.z@ardablogistics.et',
    city: 'Bahir Dar',
    licenseNumber: 'ETH-BD-44219',
    status: 'ACTIVE',
    assignedVehicleId: 'ARD-004',
    assignedVehicleReg: 'ET-3-B2115',
    activeDeliveriesCount: 0,
    completedDeliveriesCount: 284,
    rating: 4.85,
    onTimeDeliveryRate: 96.9,
    joinedDate: '2024-09-20',
  },
  {
    id: 'DRV-105',
    name: 'Tadesse Alemu',
    phone: '+251 91 223 9988',
    email: 'tadesse.a@ardablogistics.et',
    city: 'Addis Ababa',
    licenseNumber: 'ETH-AA-77441',
    status: 'ON_TRIP',
    assignedVehicleId: 'ARD-005',
    assignedVehicleReg: 'ET-3-C8814',
    currentTripId: 'TRP-1045',
    activeDeliveriesCount: 15,
    completedDeliveriesCount: 640,
    rating: 4.98,
    onTimeDeliveryRate: 99.4,
    joinedDate: '2024-02-15',
  },
];

// Trips
export const mockTrips: Trip[] = [
  {
    id: 'TRP-1042',
    city: 'Gondar',
    vehicleId: 'ARD-001',
    vehicleRegistration: 'ET-3-A4928',
    driverId: 'DRV-101',
    driverName: 'Bekele Tessema',
    driverPhone: '+251 91 190 4432',
    totalCapacityKg: 5000,
    currentLoadKg: 4350,
    remainingCapacityKg: 650,
    utilizationPercentage: 87,
    orderIds: ['ORD-9401', 'ORD-9402', 'ORD-9403', 'ORD-9404'],
    orderCount: 12,
    pickupHub: 'Gondar Central Distribution Hub',
    deliveryZones: ['Arada Central', 'Maraki Campus Zone', 'Azezo West'],
    status: 'IN_PROGRESS',
    createdTime: 'Today, 06:45 AM',
    startTime: 'Today, 07:30 AM',
    estimatedCompletionTime: 'Today, 01:30 PM',
  },
  {
    id: 'TRP-1043',
    city: 'Gondar',
    vehicleId: 'ARD-002',
    vehicleRegistration: 'ET-3-A5012',
    driverId: 'DRV-102',
    driverName: 'Dawit Haile',
    driverPhone: '+251 92 233 8812',
    totalCapacityKg: 5000,
    currentLoadKg: 4800,
    remainingCapacityKg: 200,
    utilizationPercentage: 96,
    orderIds: ['ORD-9405', 'ORD-9406', 'ORD-9407'],
    orderCount: 14,
    pickupHub: 'Gondar Central Distribution Hub',
    deliveryZones: ['Autopark Logistics Zone', 'Piazza Commercial'],
    status: 'LOADING',
    createdTime: 'Today, 08:15 AM',
    startTime: 'Today, 09:45 AM',
    estimatedCompletionTime: 'Today, 03:00 PM',
  },
  {
    id: 'TRP-1044',
    city: 'Bahir Dar',
    vehicleId: 'ARD-003',
    vehicleRegistration: 'ET-3-B2109',
    driverId: 'DRV-103',
    driverName: 'Girma Wolde',
    driverPhone: '+251 91 876 5432',
    totalCapacityKg: 5000,
    currentLoadKg: 3950,
    remainingCapacityKg: 1050,
    utilizationPercentage: 79,
    orderIds: ['ORD-9408', 'ORD-9409', 'ORD-9410'],
    orderCount: 11,
    pickupHub: 'Bahir Dar Lakefront Central Hub',
    deliveryZones: ['Kebele 04 Lakefront', 'Shimbit District', 'Gish Abay'],
    status: 'IN_PROGRESS',
    createdTime: 'Today, 07:00 AM',
    startTime: 'Today, 08:00 AM',
    estimatedCompletionTime: 'Today, 02:00 PM',
  },
  {
    id: 'TRP-1045',
    city: 'Addis Ababa',
    vehicleId: 'ARD-005',
    vehicleRegistration: 'ET-3-C8814',
    driverId: 'DRV-105',
    driverName: 'Tadesse Alemu',
    driverPhone: '+251 91 223 9988',
    totalCapacityKg: 5000,
    currentLoadKg: 4600,
    remainingCapacityKg: 400,
    utilizationPercentage: 92,
    orderIds: ['ORD-9411', 'ORD-9412', 'ORD-9413'],
    orderCount: 15,
    pickupHub: 'Kality Wholesale Logistics Center',
    deliveryZones: ['Bole Commercial Hub', 'Yeka CMC', 'Kirkos Meskel'],
    status: 'IN_PROGRESS',
    createdTime: 'Today, 06:15 AM',
    startTime: 'Today, 07:15 AM',
    estimatedCompletionTime: 'Today, 01:45 PM',
  },
  {
    id: 'TRP-1041',
    city: 'Gondar',
    vehicleId: 'ARD-001',
    vehicleRegistration: 'ET-3-A4928',
    driverId: 'DRV-101',
    driverName: 'Bekele Tessema',
    driverPhone: '+251 91 190 4432',
    totalCapacityKg: 5000,
    currentLoadKg: 4500,
    remainingCapacityKg: 500,
    utilizationPercentage: 90,
    orderIds: ['ORD-9390', 'ORD-9391'],
    orderCount: 10,
    pickupHub: 'Gondar Central Distribution Hub',
    deliveryZones: ['Arada Central'],
    status: 'COMPLETED',
    createdTime: 'Yesterday, 07:00 AM',
    startTime: 'Yesterday, 08:00 AM',
    completedTime: 'Yesterday, 02:30 PM',
  },
];

// Orders across full 8-stage lifecycle + incoming queue + exceptions
export const mockOrders: Order[] = [
  {
    id: 'ORD-9415',
    customerId: 'CUST-004',
    customerName: 'Kassahun Bekele',
    customerPhone: '+251 93 456 7890',
    city: 'Gondar',
    deliveryZone: 'Maraki Campus Zone',
    deliveryAddress: 'University Main Gate, Commercial Row #12',
    items: [
      {
        productId: 'PRD-101',
        productName: 'Magna White Teff (50 KG Bag)',
        sellerId: 'SUP-001',
        sellerName: 'Gondar Farmers Union Cooperative',
        quantity: 5,
        unitPriceEtb: 5510,
        totalPriceEtb: 27550,
        unitWeightKg: 50,
        totalWeightKg: 250,
      },
      {
        productId: 'PRD-108',
        productName: 'Traditional Spiced Clarified Butter - Kibe (10 KG)',
        sellerId: 'SUP-004',
        sellerName: 'Simien Highlands Honey & Dairy',
        quantity: 2,
        unitPriceEtb: 5580,
        totalPriceEtb: 11160,
        unitWeightKg: 10,
        totalWeightKg: 20,
      },
    ],
    subtotalEtb: 38710,
    deliveryFeeEtb: 400,
    totalEtb: 39110,
    totalWeightKg: 270,
    paymentMethod: 'TELEBIRR',
    paymentStatus: 'PAID',
    orderStatus: 'PENDING',
    timeline: [
      {
        status: 'PENDING',
        timestamp: 'Just now, 11:45 AM',
        description: 'New incoming order placed via Ardab Market mobile checkout. Awaiting admin review.',
        actor: 'Customer',
      },
    ],
    createdAt: '2025-03-13T11:45:00Z',
    updatedAt: '2025-03-13T11:45:00Z',
  },
  {
    id: 'ORD-9416',
    customerId: 'CUST-003',
    customerName: 'Hiwot Assefa',
    customerPhone: '+251 91 889 0012',
    city: 'Addis Ababa',
    deliveryZone: 'Bole Commercial Hub',
    deliveryAddress: 'Atlas Area, House 450, Bole Sub-City',
    items: [
      {
        productId: 'PRD-103',
        productName: 'Yirgacheffe Specialty Washed Coffee (10 KG)',
        sellerId: 'SUP-003',
        sellerName: 'Abyssinia Specialty Roasters',
        quantity: 8,
        unitPriceEtb: 3060,
        totalPriceEtb: 24480,
        unitWeightKg: 10,
        totalWeightKg: 80,
      },
    ],
    subtotalEtb: 24480,
    deliveryFeeEtb: 350,
    totalEtb: 24830,
    totalWeightKg: 80,
    paymentMethod: 'CBE_BIRR',
    paymentStatus: 'PAID',
    orderStatus: 'PENDING',
    timeline: [
      {
        status: 'PENDING',
        timestamp: 'Just now, 11:52 AM',
        description: 'Incoming order submitted. Payment confirmed via CBE Birr instant webhook.',
        actor: 'Customer',
      },
    ],
    createdAt: '2025-03-13T11:52:00Z',
    updatedAt: '2025-03-13T11:52:00Z',
  },
  {
    id: 'ORD-9402',
    customerId: 'CUST-001',
    customerName: 'Almaz Tadesse',
    customerPhone: '+251 91 144 8821',
    city: 'Gondar',
    deliveryZone: 'Arada Central',
    deliveryAddress: 'Near Fasil Ghebbi, House #204',
    items: [
      {
        productId: 'PRD-101',
        productName: 'Magna White Teff (50 KG Bag)',
        sellerId: 'SUP-001',
        sellerName: 'Gondar Farmers Union Cooperative',
        quantity: 10,
        unitPriceEtb: 5800,
        totalPriceEtb: 58000,
        unitWeightKg: 50,
        totalWeightKg: 500,
      },
      {
        productId: 'PRD-104',
        productName: 'Special Traditional Berbere Spice Mix (15 KG)',
        sellerId: 'SUP-002',
        sellerName: 'Tana Agro-Processing Enterprise',
        quantity: 4,
        unitPriceEtb: 4200,
        totalPriceEtb: 16800,
        unitWeightKg: 15,
        totalWeightKg: 60,
      },
    ],
    subtotalEtb: 74800,
    deliveryFeeEtb: 450,
    totalEtb: 75250,
    totalWeightKg: 560,
    paymentMethod: 'TELEBIRR',
    paymentStatus: 'PAID',
    orderStatus: 'IN_TRANSIT',
    assignedTripId: 'TRP-1042',
    assignedVehicleId: 'ARD-001',
    assignedDriverName: 'Bekele Tessema',
    timeline: [
      {
        status: 'PENDING',
        timestamp: 'Today, 06:10 AM',
        description: 'Order placed by customer through digital platform.',
        actor: 'Customer',
      },
      {
        status: 'CONFIRMED',
        timestamp: 'Today, 06:25 AM',
        description: 'Telebirr payment confirmed. Order validated.',
        actor: 'Automated System',
      },
      {
        status: 'PROCESSING',
        timestamp: 'Today, 06:40 AM',
        description: 'Goods assembled at Gondar Central Logistics Hub.',
        actor: 'Hub Operations',
      },
      {
        status: 'READY_FOR_DELIVERY',
        timestamp: 'Today, 07:05 AM',
        description: 'Batch weighed, tagged (560 KG), staging completed.',
        actor: 'Quality Inspector',
      },
      {
        status: 'ASSIGNED_TO_TRIP',
        timestamp: 'Today, 07:15 AM',
        description: 'Consolidated into Trip TRP-1042 (Vehicle ARD-001).',
        actor: 'Central Dispatch',
      },
      {
        status: 'PICKED_UP',
        timestamp: 'Today, 07:30 AM',
        description: 'Driver Bekele Tessema loaded and acknowledged consignment.',
        actor: 'Driver Bekele T.',
      },
      {
        status: 'IN_TRANSIT',
        timestamp: 'Today, 08:00 AM',
        description: 'En route to Arada Central destination zone.',
        actor: 'Fleet Telemetry',
      },
    ],
    createdAt: '2025-03-13T06:10:00Z',
    updatedAt: '2025-03-13T08:00:00Z',
  },
  {
    id: 'ORD-9403',
    customerId: 'CUST-002',
    customerName: 'Solomon Mengistu',
    customerPhone: '+251 92 334 1109',
    city: 'Bahir Dar',
    deliveryZone: 'Kebele 04 Lakefront',
    deliveryAddress: 'Bole Road, Near Palm Palace Hotel',
    items: [
      {
        productId: 'PRD-102',
        productName: 'Sergegna Mixed Teff (50 KG Bag)',
        sellerId: 'SUP-001',
        sellerName: 'Gondar Farmers Union Cooperative',
        quantity: 8,
        unitPriceEtb: 4950,
        totalPriceEtb: 39600,
        unitWeightKg: 50,
        totalWeightKg: 400,
      },
      {
        productId: 'PRD-106',
        productName: 'Refined Nug (Niger Seed) Cooking Oil (20L Jerrycan)',
        sellerId: 'SUP-004',
        sellerName: 'Simien Highlands Honey & Dairy',
        quantity: 5,
        unitPriceEtb: 4600,
        totalPriceEtb: 23000,
        unitWeightKg: 19,
        totalWeightKg: 95,
      },
    ],
    subtotalEtb: 62600,
    deliveryFeeEtb: 420,
    totalEtb: 63020,
    totalWeightKg: 495,
    paymentMethod: 'CBE_BIRR',
    paymentStatus: 'PAID',
    orderStatus: 'IN_TRANSIT',
    assignedTripId: 'TRP-1044',
    assignedVehicleId: 'ARD-003',
    assignedDriverName: 'Girma Wolde',
    timeline: [
      {
        status: 'PENDING',
        timestamp: 'Today, 06:30 AM',
        description: 'Order placed with CBE Birr payment.',
        actor: 'Customer',
      },
      {
        status: 'CONFIRMED',
        timestamp: 'Today, 06:45 AM',
        description: 'CBE Birr API verified.',
        actor: 'Finance Gateway',
      },
      {
        status: 'ASSIGNED_TO_TRIP',
        timestamp: 'Today, 07:15 AM',
        description: 'Assigned to Trip TRP-1044.',
        actor: 'Dispatcher Bahir Dar',
      },
      {
        status: 'IN_TRANSIT',
        timestamp: 'Today, 08:15 AM',
        description: 'Vehicle ARD-003 departing station.',
        actor: 'Driver Girma W.',
      },
    ],
    createdAt: '2025-03-13T06:30:00Z',
    updatedAt: '2025-03-13T08:15:00Z',
  },
  {
    id: 'ORD-9404',
    customerId: 'CUST-003',
    customerName: 'Hiwot Assefa',
    customerPhone: '+251 91 889 0012',
    city: 'Addis Ababa',
    deliveryZone: 'Bole Commercial Hub',
    deliveryAddress: 'Atlas Area, House 450, Bole Sub-City',
    items: [
      {
        productId: 'PRD-103',
        productName: 'Yirgacheffe Specialty Washed Coffee (10 KG)',
        sellerId: 'SUP-003',
        sellerName: 'Abyssinia Specialty Roasters',
        quantity: 12,
        unitPriceEtb: 3400,
        totalPriceEtb: 40800,
        unitWeightKg: 10,
        totalWeightKg: 120,
      },
      {
        productId: 'PRD-105',
        productName: 'Pure White Highlands Honey (25 KG Bucket)',
        sellerId: 'SUP-004',
        sellerName: 'Simien Highlands Honey & Dairy',
        quantity: 4,
        unitPriceEtb: 8500,
        totalPriceEtb: 34000,
        unitWeightKg: 25,
        totalWeightKg: 100,
      },
    ],
    subtotalEtb: 74800,
    deliveryFeeEtb: 550,
    totalEtb: 75350,
    totalWeightKg: 220,
    paymentMethod: 'TELEBIRR',
    paymentStatus: 'PAID',
    orderStatus: 'IN_TRANSIT',
    assignedTripId: 'TRP-1045',
    assignedVehicleId: 'ARD-005',
    assignedDriverName: 'Tadesse Alemu',
    timeline: [
      {
        status: 'CONFIRMED',
        timestamp: 'Today, 06:15 AM',
        description: 'Order confirmed and scheduled.',
        actor: 'Dispatcher AA',
      },
      {
        status: 'IN_TRANSIT',
        timestamp: 'Today, 07:30 AM',
        description: 'Truck dispatched from Kaliti wholesale hub.',
        actor: 'Driver Tadesse A.',
      },
    ],
    createdAt: '2025-03-13T06:00:00Z',
    updatedAt: '2025-03-13T07:30:00Z',
  },
  {
    id: 'ORD-9405',
    customerId: 'CUST-004',
    customerName: 'Kassahun Bekele',
    customerPhone: '+251 93 456 7890',
    city: 'Gondar',
    deliveryZone: 'Maraki Campus Zone',
    deliveryAddress: 'University Main Gate, Commercial Row #12',
    items: [
      {
        productId: 'PRD-101',
        productName: 'Magna White Teff (50 KG Bag)',
        sellerId: 'SUP-001',
        sellerName: 'Gondar Farmers Union Cooperative',
        quantity: 6,
        unitPriceEtb: 5800,
        totalPriceEtb: 34800,
        unitWeightKg: 50,
        totalWeightKg: 300,
      },
    ],
    subtotalEtb: 34800,
    deliveryFeeEtb: 350,
    totalEtb: 35150,
    totalWeightKg: 300,
    paymentMethod: 'CASH_ON_DELIVERY',
    paymentStatus: 'PENDING',
    orderStatus: 'PROCESSING',
    timeline: [
      {
        status: 'PENDING',
        timestamp: 'Today, 08:15 AM',
        description: 'Order placed, awaiting packaging.',
        actor: 'System',
      },
      {
        status: 'PROCESSING',
        timestamp: 'Today, 08:45 AM',
        description: 'Sacks verified at staging shelf.',
        actor: 'Warehouse Staff',
      },
    ],
    createdAt: '2025-03-13T08:15:00Z',
    updatedAt: '2025-03-13T08:45:00Z',
  },
  {
    id: 'ORD-9406',
    customerId: 'CUST-005',
    customerName: 'Birtukan Lemma',
    customerPhone: '+251 94 512 3456',
    city: 'Bahir Dar',
    deliveryZone: 'Shimbit District',
    deliveryAddress: 'Opposite Tana Secondary School',
    items: [
      {
        productId: 'PRD-107',
        productName: 'Highland Red Split Lentils - Misir (25 KG)',
        sellerId: 'SUP-005',
        sellerName: 'Gojjam Pulses & Legumes Millers',
        quantity: 5,
        unitPriceEtb: 3800,
        totalPriceEtb: 19000,
        unitWeightKg: 25,
        totalWeightKg: 125,
      },
    ],
    subtotalEtb: 19000,
    deliveryFeeEtb: 300,
    totalEtb: 19300,
    totalWeightKg: 125,
    paymentMethod: 'TELEBIRR',
    paymentStatus: 'PAID',
    orderStatus: 'READY_FOR_DELIVERY',
    timeline: [
      {
        status: 'READY_FOR_DELIVERY',
        timestamp: 'Today, 09:00 AM',
        description: 'Prepared for afternoon dispatch run.',
        actor: 'Logistics Lead',
      },
    ],
    createdAt: '2025-03-13T08:30:00Z',
    updatedAt: '2025-03-13T09:00:00Z',
  },
  {
    id: 'ORD-9390',
    customerId: 'CUST-001',
    customerName: 'Almaz Tadesse',
    customerPhone: '+251 91 144 8821',
    city: 'Gondar',
    deliveryZone: 'Arada Central',
    deliveryAddress: 'Near Fasil Ghebbi, House #204',
    items: [
      {
        productId: 'PRD-108',
        productName: 'Traditional Spiced Clarified Butter - Kibe (10 KG)',
        sellerId: 'SUP-004',
        sellerName: 'Simien Highlands Honey & Dairy',
        quantity: 2,
        unitPriceEtb: 6200,
        totalPriceEtb: 12400,
        unitWeightKg: 10,
        totalWeightKg: 20,
      },
    ],
    subtotalEtb: 12400,
    deliveryFeeEtb: 250,
    totalEtb: 12650,
    totalWeightKg: 20,
    paymentMethod: 'TELEBIRR',
    paymentStatus: 'PAID',
    orderStatus: 'DELIVERED',
    assignedTripId: 'TRP-1041',
    assignedVehicleId: 'ARD-001',
    assignedDriverName: 'Bekele Tessema',
    timeline: [
      {
        status: 'DELIVERED',
        timestamp: 'Yesterday, 02:15 PM',
        description: 'Successfully handed over to customer with OTP confirmation.',
        actor: 'Driver Bekele T.',
      },
    ],
    createdAt: '2025-03-12T07:00:00Z',
    updatedAt: '2025-03-12T14:15:00Z',
  },
  {
    id: 'ORD-9388',
    customerId: 'CUST-006',
    customerName: 'Yonas Gebre',
    customerPhone: '+251 95 678 9012',
    city: 'Addis Ababa',
    deliveryZone: 'Yeka CMC',
    deliveryAddress: 'CMC Michael Commercial Center #30',
    items: [
      {
        productId: 'PRD-101',
        productName: 'Magna White Teff (50 KG Bag)',
        sellerId: 'SUP-001',
        sellerName: 'Gondar Farmers Union Cooperative',
        quantity: 1,
        unitPriceEtb: 5800,
        totalPriceEtb: 5800,
        unitWeightKg: 50,
        totalWeightKg: 50,
      },
    ],
    subtotalEtb: 5800,
    deliveryFeeEtb: 300,
    totalEtb: 6100,
    totalWeightKg: 50,
    paymentMethod: 'TELEBIRR',
    paymentStatus: 'REFUNDED',
    orderStatus: 'CANCELLED',
    timeline: [
      {
        status: 'CANCELLED',
        timestamp: '2025-03-10, 11:30 AM',
        description: 'Customer requested cancellation prior to load dispatch. Refund issued.',
        actor: 'Super Admin',
      },
    ],
    createdAt: '2025-03-10T10:00:00Z',
    updatedAt: '2025-03-10T11:30:00Z',
  },
];

// Finance
export const mockRevenueMetrics: RevenueMetrics = {
  totalRevenueEtb: 4895400,
  todayRevenueEtb: 342650,
  weeklyRevenueEtb: 1845000,
  monthlyRevenueEtb: 4895400,
  totalDeliveryFeesEtb: 218400,
  completedOrdersRevenueEtb: 4620000,
  refundsCancellationsEtb: 57000,
  growthPercentage: 16.4,
};

export const mockTransactions: Transaction[] = [
  {
    id: 'TXN-88219',
    orderId: 'ORD-9402',
    customerName: 'Almaz Tadesse',
    amountEtb: 75250,
    paymentMethod: 'TELEBIRR',
    paymentStatus: 'PAID',
    city: 'Gondar',
    timestamp: 'Today, 06:25 AM',
  },
  {
    id: 'TXN-88220',
    orderId: 'ORD-9403',
    customerName: 'Solomon Mengistu',
    amountEtb: 63020,
    paymentMethod: 'CBE_BIRR',
    paymentStatus: 'PAID',
    city: 'Bahir Dar',
    timestamp: 'Today, 06:45 AM',
  },
  {
    id: 'TXN-88221',
    orderId: 'ORD-9404',
    customerName: 'Hiwot Assefa',
    amountEtb: 75350,
    paymentMethod: 'TELEBIRR',
    paymentStatus: 'PAID',
    city: 'Addis Ababa',
    timestamp: 'Today, 06:15 AM',
  },
  {
    id: 'TXN-88222',
    orderId: 'ORD-9406',
    customerName: 'Birtukan Lemma',
    amountEtb: 19300,
    paymentMethod: 'TELEBIRR',
    paymentStatus: 'PAID',
    city: 'Bahir Dar',
    timestamp: 'Today, 08:35 AM',
  },
  {
    id: 'TXN-88210',
    orderId: 'ORD-9390',
    customerName: 'Almaz Tadesse',
    amountEtb: 12650,
    paymentMethod: 'TELEBIRR',
    paymentStatus: 'PAID',
    city: 'Gondar',
    timestamp: 'Yesterday, 07:15 AM',
  },
  {
    id: 'TXN-88200',
    orderId: 'ORD-9388',
    customerName: 'Yonas Gebre',
    amountEtb: 6100,
    paymentMethod: 'TELEBIRR',
    paymentStatus: 'REFUNDED',
    city: 'Addis Ababa',
    timestamp: '2025-03-10, 11:30 AM',
  },
];

// Reports & Analytics
export const mockSalesByCity: SalesByCity[] = [
  { city: 'Gondar', revenueEtb: 1980000, orderCount: 380, deliveredPercentage: 99.1 },
  { city: 'Bahir Dar', revenueEtb: 1540000, orderCount: 295, deliveredPercentage: 98.4 },
  { city: 'Addis Ababa', revenueEtb: 1375400, orderCount: 245, deliveredPercentage: 97.8 },
];

export const mockSalesByCategory: SalesByCategory[] = [
  { category: 'Grains & Cereals', revenueEtb: 2450000, weightSoldKg: 38500, percentage: 50.1 },
  { category: 'Coffee & Spices', revenueEtb: 980000, weightSoldKg: 6400, percentage: 20.0 },
  { category: 'Edible Oils & Seeds', revenueEtb: 620000, weightSoldKg: 4200, percentage: 12.7 },
  { category: 'Honey & Sweeteners', revenueEtb: 480000, weightSoldKg: 2100, percentage: 9.8 },
  { category: 'Pulses & Legumes', revenueEtb: 365400, weightSoldKg: 3800, percentage: 7.4 },
];

export const mockOperationalPerformance: OperationalPerformance = {
  deliverySuccessRate: 98.7,
  avgDeliveryTimeMinutes: 42,
  fleetCapacityUtilization: 86.4,
  activeFleetCount: 5,
  customerGrowthRate: 15.8,
};

export const mockNotifications: Notification[] = [];

// Security & Super Admin Accounts
export const mockAdminUsers: AdminUser[] = [
  {
    id: 'ADM-001',
    name: 'Abebe Kebede',
    email: 'admin@ardabmarket.com',
    role: 'SUPER_ADMIN',
    status: 'ACTIVE',
    phone: '+251 91 123 4567',
    lastLogin: 'Today, 09:15 AM',
    assignedCities: ['Gondar', 'Bahir Dar', 'Addis Ababa'],
    createdAt: '2025-01-10',
  },
  {
    id: 'ADM-004',
    name: 'Dawit Wolde',
    email: 'dawit.admin@ardabmarket.com',
    role: 'SUPER_ADMIN',
    status: 'ACTIVE',
    phone: '+251 91 332 1122',
    lastLogin: 'Yesterday, 03:40 PM',
    assignedCities: ['Gondar', 'Bahir Dar'],
    createdAt: '2025-02-01',
  },
  {
    id: 'ADM-005',
    name: 'Tigist Alemayehu',
    email: 'tigist.admin@ardabmarket.com',
    role: 'SUPER_ADMIN',
    status: 'SUSPENDED',
    phone: '+251 92 445 6677',
    lastLogin: '5 days ago',
    assignedCities: ['Addis Ababa'],
    createdAt: '2025-02-15',
  },
  {
    id: 'ADM-002',
    name: 'Meron Tesfaye',
    email: 'meron.t@ardabmarket.com',
    role: 'OPERATIONS_MANAGER',
    status: 'ACTIVE',
    phone: '+251 91 889 2233',
    lastLogin: 'Today, 08:30 AM',
    assignedCities: ['Gondar', 'Bahir Dar'],
    createdAt: '2025-01-18',
  },
  {
    id: 'ADM-003',
    name: 'Henok Girma',
    email: 'henok.g@ardabmarket.com',
    role: 'DISPATCHER',
    status: 'ACTIVE',
    phone: '+251 93 455 6677',
    lastLogin: 'Today, 07:00 AM',
    assignedCities: ['Addis Ababa'],
    createdAt: '2025-01-22',
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'LOG-501',
    adminName: 'Abebe Kebede',
    adminEmail: 'admin@ardabmarket.com',
    action: 'DISPATCH_TRIP',
    entity: 'Trip',
    entityId: 'TRP-1042',
    ipAddress: '197.156.104.22 (Ethio Telecom)',
    timestamp: 'Today, 07:30 AM',
    changesSummary: 'Status changed from READY to IN_PROGRESS. Assigned ARD-001.',
  },
  {
    id: 'LOG-502',
    adminName: 'Meron Tesfaye',
    adminEmail: 'meron.t@ardabmarket.com',
    action: 'UPDATE_PRODUCT_PRICE',
    entity: 'Product',
    entityId: 'PRD-101',
    ipAddress: '197.156.110.15 (Ethio Telecom)',
    timestamp: 'Yesterday, 04:15 PM',
    changesSummary: 'Selling price updated from 5,600 ETB to 5,800 ETB.',
  },
  {
    id: 'LOG-503',
    adminName: 'Abebe Kebede',
    adminEmail: 'admin@ardabmarket.com',
    action: 'SUSPEND_CUSTOMER',
    entity: 'Customer',
    entityId: 'CUST-006',
    ipAddress: '197.156.104.22 (Ethio Telecom)',
    timestamp: '2025-03-10, 11:35 AM',
    changesSummary: 'Account status set to SUSPENDED due to unverified high dispute.',
  },
];

// Settings - Country -> City -> Delivery Zone -> Neighborhood
export const mockCitiesConfig: CityConfig[] = [
  {
    id: 'CITY-GD',
    name: 'Gondar',
    country: 'Ethiopia',
    hubAddress: 'Arada Logistics Hub, Commercial Zone, Gondar',
    contactPhone: '+251 58 111 2233',
    isActive: true,
    totalVehicles: 2,
    totalDrivers: 2,
    zones: [
      {
        id: 'ZN-GD-01',
        name: 'Arada Central',
        code: 'GD-ARA',
        cityId: 'CITY-GD',
        baseDeliveryFeeEtb: 250,
        perKgFeeEtb: 1.5,
        estimatedDeliveryHours: '2-4 hours',
        isActive: true,
        neighborhoods: [
          { id: 'NH-01', name: 'Fasil Ghebbi Area' },
          { id: 'NH-02', name: 'Piazza Gondar' },
          { id: 'NH-03', name: 'Gebeya Meda' },
        ],
      },
      {
        id: 'ZN-GD-02',
        name: 'Maraki Campus Zone',
        code: 'GD-MRK',
        cityId: 'CITY-GD',
        baseDeliveryFeeEtb: 300,
        perKgFeeEtb: 1.8,
        estimatedDeliveryHours: '3-5 hours',
        isActive: true,
        neighborhoods: [
          { id: 'NH-04', name: 'University Campus' },
          { id: 'NH-05', name: 'Maraki Commercial' },
        ],
      },
      {
        id: 'ZN-GD-03',
        name: 'Azezo West Hub',
        code: 'GD-AZZ',
        cityId: 'CITY-GD',
        baseDeliveryFeeEtb: 350,
        perKgFeeEtb: 2.0,
        estimatedDeliveryHours: '4-6 hours',
        isActive: true,
        neighborhoods: [
          { id: 'NH-06', name: 'Azezo Airport Road' },
          { id: 'NH-07', name: 'Teklehaimanot' },
        ],
      },
    ],
  },
  {
    id: 'CITY-BD',
    name: 'Bahir Dar',
    country: 'Ethiopia',
    hubAddress: 'Lake Tana Gateway Depot, Bahir Dar',
    contactPhone: '+251 58 220 4455',
    isActive: true,
    totalVehicles: 2,
    totalDrivers: 2,
    zones: [
      {
        id: 'ZN-BD-01',
        name: 'Kebele 04 Lakefront',
        code: 'BD-K04',
        cityId: 'CITY-BD',
        baseDeliveryFeeEtb: 260,
        perKgFeeEtb: 1.6,
        estimatedDeliveryHours: '2-4 hours',
        isActive: true,
        neighborhoods: [
          { id: 'NH-08', name: 'Palm Palace Lakefront' },
          { id: 'NH-09', name: 'Avanti Corridor' },
        ],
      },
      {
        id: 'ZN-BD-02',
        name: 'Shimbit District',
        code: 'BD-SHM',
        cityId: 'CITY-BD',
        baseDeliveryFeeEtb: 300,
        perKgFeeEtb: 1.7,
        estimatedDeliveryHours: '3-5 hours',
        isActive: true,
        neighborhoods: [
          { id: 'NH-10', name: 'Tana Secondary Area' },
          { id: 'NH-11', name: 'Shimbit Market' },
        ],
      },
    ],
  },
  {
    id: 'CITY-AA',
    name: 'Addis Ababa',
    country: 'Ethiopia',
    hubAddress: 'Kaliti Industrial Logistic Station, Addis Ababa',
    contactPhone: '+251 11 440 9988',
    isActive: true,
    totalVehicles: 2,
    totalDrivers: 1,
    zones: [
      {
        id: 'ZN-AA-01',
        name: 'Bole Commercial Hub',
        code: 'AA-BOL',
        cityId: 'CITY-AA',
        baseDeliveryFeeEtb: 350,
        perKgFeeEtb: 2.2,
        estimatedDeliveryHours: '3-5 hours',
        isActive: true,
        neighborhoods: [
          { id: 'NH-12', name: 'Bole Atlas' },
          { id: 'NH-13', name: 'Bole Medhanealem' },
          { id: 'NH-14', name: 'Edna Mall District' },
        ],
      },
      {
        id: 'ZN-AA-02',
        name: 'Yeka CMC',
        code: 'AA-YEK',
        cityId: 'CITY-AA',
        baseDeliveryFeeEtb: 380,
        perKgFeeEtb: 2.4,
        estimatedDeliveryHours: '4-6 hours',
        isActive: true,
        neighborhoods: [
          { id: 'NH-15', name: 'CMC Michael' },
          { id: 'NH-16', name: 'Gurd Shola Commercial' },
        ],
      },
    ],
  },
];

export const mockPlatformSettings: PlatformSettings = {
  platformName: 'Ardab Market Super Admin',
  supportPhone: '+251 91 123 4567',
  supportEmail: 'ops@ardabmarket.com',
  defaultVehicleCapacityKg: 5000,
  orderCancellationGracePeriodMinutes: 30,
  enableTelebirrAutoVerification: true,
  enableCbeBirrAutoVerification: true,
  maintenanceNoticeActive: false,
};

// ==========================================
// SUB ADMIN: 1. Customer Support Tickets
// ==========================================
export const mockSupportTickets: SupportTicket[] = [
  {
    id: 'TCK-501',
    ticketNumber: 'SUP-2025-0501',
    customerId: 'CUST-001',
    customerName: 'Almaz Tadesse',
    customerPhone: '+251 91 144 8821',
    city: 'Gondar',
    subject: 'Magna Teff Bag Delivery Time Query',
    category: 'ORDER_ISSUE',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    assignedTo: 'Eden Tilahun',
    orderId: 'ORD-9402',
    createdAt: '2025-03-13T09:15:00Z',
    updatedAt: '2025-03-13T10:00:00Z',
    messages: [
      {
        id: 'MSG-01',
        senderName: 'Almaz Tadesse',
        senderType: 'CUSTOMER',
        message: 'Hello, my order ORD-9402 has 10 sacks of Magna Teff. When will the truck arrive at Arada Central near Fasil Ghebbi?',
        timestamp: '09:15 AM',
      },
      {
        id: 'MSG-02',
        senderName: 'Eden Tilahun',
        senderType: 'SUB_ADMIN',
        message: 'Dear Almaz, your order is loaded on vehicle ARD-001 with driver Bekele Tessema. Estimated arrival is 11:30 AM. He will call you upon reaching the gate.',
        timestamp: '10:00 AM',
      },
    ],
  },
  {
    id: 'TCK-502',
    ticketNumber: 'SUP-2025-0502',
    customerId: 'CUST-002',
    customerName: 'Solomon Mengistu',
    customerPhone: '+251 92 334 1109',
    city: 'Bahir Dar',
    subject: 'Telebirr Payment SMS Confirmation Delayed',
    category: 'PAYMENT_DISPUTE',
    priority: 'URGENT',
    status: 'OPEN',
    assignedTo: 'Eden Tilahun',
    orderId: 'ORD-9403',
    createdAt: '2025-03-13T10:30:00Z',
    updatedAt: '2025-03-13T10:30:00Z',
    messages: [
      {
        id: 'MSG-03',
        senderName: 'Solomon Mengistu',
        senderType: 'CUSTOMER',
        message: 'I transferred 63,020 ETB via Telebirr for order ORD-9403. Money was deducted but app says pending verification.',
        timestamp: '10:30 AM',
      },
    ],
  },
  {
    id: 'TCK-503',
    ticketNumber: 'SUP-2025-0503',
    customerId: 'CUST-003',
    customerName: 'Hiwot Assefa',
    customerPhone: '+251 91 889 0012',
    city: 'Addis Ababa',
    subject: 'Honey Packaging Seal Quality Inspection',
    category: 'PRODUCT_QUALITY',
    priority: 'MEDIUM',
    status: 'RESOLVED',
    assignedTo: 'Eden Tilahun',
    orderId: 'ORD-9404',
    createdAt: '2025-03-12T14:20:00Z',
    updatedAt: '2025-03-12T16:00:00Z',
    resolutionNotes: 'Verified with supplier Simien Highlands Honey. Replacement bucket seal verified and dispatched with courier apology voucher.',
    messages: [
      {
        id: 'MSG-04',
        senderName: 'Hiwot Assefa',
        senderType: 'CUSTOMER',
        message: 'Can you verify if the 25 KG white honey bucket is hermetically sealed before Kaliti warehouse dispatch?',
        timestamp: '02:20 PM',
      },
      {
        id: 'MSG-05',
        senderName: 'Eden Tilahun',
        senderType: 'SUB_ADMIN',
        message: 'Quality inspector verified Grade-1 heat-sealed silicone rim. Photos uploaded to your account.',
        timestamp: '04:00 PM',
      },
    ],
  },
  {
    id: 'TCK-504',
    ticketNumber: 'SUP-2025-0504',
    customerId: 'CUST-004',
    customerName: 'Kassahun Bekele',
    customerPhone: '+251 93 456 7890',
    city: 'Gondar',
    subject: 'Maraki Campus Delivery Gate Access Clarification',
    category: 'DELIVERY_DELAY',
    priority: 'LOW',
    status: 'CLOSED',
    assignedTo: 'Eden Tilahun',
    createdAt: '2025-03-11T11:00:00Z',
    updatedAt: '2025-03-11T12:15:00Z',
    resolutionNotes: 'Updated destination zone instructions to use Commercial Row gate #2 for 5T truck access.',
    messages: [
      {
        id: 'MSG-06',
        senderName: 'Kassahun Bekele',
        senderType: 'CUSTOMER',
        message: 'Large trucks cannot enter main student gate. Please instruct driver to use commercial delivery gate #2.',
        timestamp: '11:00 AM',
      },
    ],
  },
];

// ==========================================
// SUB ADMIN: 2. Security Management
// ==========================================
export const mockActiveSessions: ActiveSession[] = [
  {
    id: 'SES-001',
    userId: 'ADM-001',
    userName: 'Abebe Kebede',
    userEmail: 'admin@ardabmarket.com',
    role: 'SUPER_ADMIN',
    device: 'Windows Desktop (Chrome 122)',
    browser: 'Chrome 122 / Windows 11',
    ipAddress: '197.156.102.44',
    location: 'Addis Ababa, Ethiopia (Ethio Telecom)',
    startedAt: 'Today, 08:30 AM',
    lastActive: 'Just now',
    status: 'ACTIVE',
  },
  {
    id: 'SES-002',
    userId: 'ADM-SUB-001',
    userName: 'Eden Tilahun',
    userEmail: 'subadmin@ardabmarket.com',
    role: 'SUB_ADMIN',
    device: 'MacBook Pro (Firefox 123)',
    browser: 'Firefox 123 / macOS',
    ipAddress: '197.156.98.12',
    location: 'Gondar Central Ops, Ethiopia',
    startedAt: 'Today, 09:10 AM',
    lastActive: '2 minutes ago',
    status: 'ACTIVE',
  },
  {
    id: 'SES-003',
    userId: 'DRV-101',
    userName: 'Bekele Tessema',
    userEmail: 'bekele.t@ardablogistics.et',
    role: 'DISPATCHER',
    device: 'Samsung Galaxy Tab A8',
    browser: 'Ardab Driver Mobile v2.1',
    ipAddress: '197.156.88.204',
    location: 'Gondar - Fleet Terminal ARD-001',
    startedAt: 'Today, 06:45 AM',
    lastActive: '5 minutes ago',
    status: 'ACTIVE',
  },
];

export const mockSecurityAlerts: SecurityAlert[] = [
  {
    id: 'ALT-101',
    severity: 'LOW',
    title: 'Multiple Concurrent Admin Logins Detected',
    description: 'Super Admin account logged in from 2 distinct IP ranges in Addis Ababa within 15 minutes.',
    ipAddress: '197.156.102.44',
    timestamp: 'Today at 08:32 AM',
    resolved: true,
    resolvedBy: 'Eden Tilahun',
  },
  {
    id: 'ALT-102',
    severity: 'HIGH',
    title: 'Automated Scraping Attempt on Product Prices',
    description: 'Rate-limiter triggered by 420 requests/minute to public products catalog endpoint from unregistered proxy IP.',
    ipAddress: '185.220.101.5',
    timestamp: 'Today at 06:12 AM',
    resolved: false,
  },
  {
    id: 'ALT-103',
    severity: 'MEDIUM',
    title: 'Unusual Order Volume from Single IP',
    description: '5 rapid checkout attempts in under 60 seconds with mismatched CBE Birr account names.',
    ipAddress: '197.156.77.89',
    timestamp: 'Yesterday at 11:45 PM',
    resolved: true,
    resolvedBy: 'Eden Tilahun',
  },
];

export const mockIpBlockRules: IpBlockRule[] = [
  {
    id: 'IPR-001',
    ipAddress: '185.220.101.5',
    reason: 'Suspicious DDoS/crawler scanning /api/products endpoints',
    blockedAt: '2025-03-13 06:15 AM',
    blockedBy: 'Eden Tilahun (Sub Admin)',
    status: 'BLOCKED',
  },
  {
    id: 'IPR-002',
    ipAddress: '197.156.102.0/24',
    reason: 'Ardab Regional Headquarters Subnet Whitelist',
    blockedAt: '2025-01-10',
    blockedBy: 'Super Admin',
    status: 'WHITELISTED',
  },
];

export const mockFailedLogins: FailedLoginLog[] = [
  {
    id: 'FL-001',
    attemptedEmail: 'root@ardabmarket.com',
    ipAddress: '185.220.101.5',
    timestamp: 'Today at 06:14 AM',
    city: 'Unknown',
    reason: 'Invalid username credentials',
    blocked: true,
  },
  {
    id: 'FL-002',
    attemptedEmail: 'admin@ardabmarket.com',
    ipAddress: '197.156.65.18',
    timestamp: 'Today at 07:22 AM',
    city: 'Bahir Dar',
    reason: 'Password authentication failed (attempt 1/5)',
    blocked: false,
  },
];

// ==========================================
// SUB ADMIN: 3. Maintenance Management
// ==========================================
export const mockSystemServices: SystemService[] = [
  {
    id: 'SRV-01',
    name: 'Core Marketplace API Gateway',
    category: 'CORE_API',
    status: 'HEALTHY',
    latencyMs: 38,
    uptimePercentage: 99.98,
    lastChecked: '30s ago',
    serverNode: 'node-et-prod-01.addis',
  },
  {
    id: 'SRV-02',
    name: 'PostgreSQL Database Cluster',
    category: 'DATABASE',
    status: 'HEALTHY',
    latencyMs: 12,
    uptimePercentage: 99.99,
    lastChecked: '15s ago',
    serverNode: 'pg-primary.ethio-cloud',
  },
  {
    id: 'SRV-03',
    name: 'PostGIS Spatial & Routing Engine',
    category: 'GIS_ENGINE',
    status: 'HEALTHY',
    latencyMs: 44,
    uptimePercentage: 99.95,
    lastChecked: '45s ago',
    serverNode: 'gis-geo.gondar-cluster',
  },
  {
    id: 'SRV-04',
    name: 'Redis Queue & Session Store',
    category: 'CACHE',
    status: 'HEALTHY',
    latencyMs: 4,
    uptimePercentage: 100,
    lastChecked: '10s ago',
    serverNode: 'redis-memory-cache-01',
  },
  {
    id: 'SRV-05',
    name: '5,000 KG Fleet GPS Telemetry Sync',
    category: 'TELEMETRY',
    status: 'HEALTHY',
    latencyMs: 65,
    uptimePercentage: 99.89,
    lastChecked: '5s ago',
    serverNode: 'telemetry-broker-fleet',
  },
  {
    id: 'SRV-06',
    name: 'Telebirr & CBE Birr Payment Webhook',
    category: 'PAYMENTS',
    status: 'HEALTHY',
    latencyMs: 82,
    uptimePercentage: 99.92,
    lastChecked: '1m ago',
    serverNode: 'pay-webhook-gateway',
  },
];

export const mockMaintenanceWindows: MaintenanceWindow[] = [
  {
    id: 'MW-201',
    title: 'PostgreSQL Spatial Index Defragmentation & Backup',
    description: 'Scheduled index vacuuming on delivery zones and boundary polygons for Gondar and Bahir Dar regional hubs.',
    scheduledStartTime: 'Sunday, March 16, 02:00 AM',
    scheduledEndTime: 'Sunday, March 16, 03:30 AM',
    status: 'SCHEDULED',
    affectedServices: ['PostGIS Spatial & Routing Engine', 'PostgreSQL Database Cluster'],
    announcedToUsers: true,
    createdBy: 'Eden Tilahun (Sub Admin)',
  },
  {
    id: 'MW-200',
    title: 'SSL Certificate & Token Vault Refresh',
    description: 'Zero-downtime certificate renewal and API token secret rotation across cloud gateways.',
    scheduledStartTime: 'Last Sunday, 01:00 AM',
    scheduledEndTime: 'Last Sunday, 01:25 AM',
    status: 'COMPLETED',
    affectedServices: ['Core Marketplace API Gateway'],
    announcedToUsers: false,
    createdBy: 'Super Admin',
  },
];

export const mockMaintenanceTasks: MaintenanceTask[] = [
  {
    id: 'TSK-01',
    name: 'PostgreSQL Auto-Vacuum & Analyze',
    category: 'DATABASE',
    description: 'Reclaim dead tuple storage and recalculate planner optimizer statistics.',
    frequency: 'Daily at 03:00 AM',
    lastRun: 'Today, 03:00 AM',
    status: 'SUCCESS',
    lastDurationMs: 4200,
  },
  {
    id: 'TSK-02',
    name: 'Purge Expired Redis Sessions & Rate Limits',
    category: 'CACHE',
    description: 'Clean up stale user authentication cookies and rate limit buckets.',
    frequency: 'Every 6 hours',
    lastRun: 'Today, 06:00 AM',
    status: 'SUCCESS',
    lastDurationMs: 850,
  },
  {
    id: 'TSK-03',
    name: 'Automated Snapshot to Offsite Cold Storage',
    category: 'STORAGE',
    description: 'Export encrypted daily database snapshot to isolated regional storage.',
    frequency: 'Daily at 04:00 AM',
    lastRun: 'Today, 04:00 AM',
    status: 'SUCCESS',
    lastDurationMs: 18500,
  },
  {
    id: 'TSK-04',
    name: 'System Vulnerability & Port Scan Audit',
    category: 'SECURITY',
    description: 'Automated port scanner verifying zero exposed administrative endpoints.',
    frequency: 'Weekly',
    lastRun: 'Yesterday, 11:00 PM',
    status: 'SUCCESS',
    lastDurationMs: 6400,
  },
];

export const mockEquipmentLogs: EquipmentServiceLog[] = [
  {
    id: 'EQ-01',
    vehicleId: 'ARD-001',
    vehicleReg: 'ET-3-A4928',
    serviceType: '5,000 KM Hydraulic Brake Inspection & Oil Change',
    city: 'Gondar',
    workshopLocation: 'Azezo Heavy Fleet Repair Center',
    costEtb: 8500,
    scheduledDate: '2025-03-20',
    status: 'SCHEDULED',
    technicianNotes: 'Brake pads at 65% remaining wear. Routine filter changes scheduled.',
  },
  {
    id: 'EQ-02',
    vehicleId: 'ARD-006',
    vehicleReg: 'ET-3-C8820',
    serviceType: 'Suspension Bushing & Rear Axle Torque Alignment',
    city: 'Addis Ababa',
    workshopLocation: 'Kaliti Isuzu Authorized Workshop',
    costEtb: 14200,
    scheduledDate: '2025-03-10',
    status: 'IN_PROGRESS',
    technicianNotes: 'Parts arrived from supplier. Final wheel alignment underway.',
  },
];

// ==========================================
// SUB ADMIN: 4. Feedback Management
// ==========================================
export const mockFeedbackMetrics: FeedbackMetrics = {
  averageRating: 4.85,
  totalReviews: 342,
  netPromoterScore: 86,
  positivePercentage: 92,
  neutralPercentage: 6,
  negativePercentage: 2,
};

export const mockFeedbackItems: FeedbackItem[] = [
  {
    id: 'FB-001',
    type: 'PRODUCT',
    authorName: 'Almaz Tadesse',
    authorRole: 'CUSTOMER',
    city: 'Gondar',
    rating: 5,
    title: 'Finest Magna White Teff in Gondar',
    comment: 'The teff from Gondar Farmers Union is pure white, thoroughly cleaned with zero dirt or sand. Injera turned out exceptionally soft!',
    targetEntityName: 'Magna White Teff (50 KG Bag)',
    status: 'REVIEWED',
    sentiment: 'POSITIVE',
    createdAt: 'Today, 08:45 AM',
    adminReply: 'Thank you Almaz! Gondar Farmers Union takes pride in their Grade-A sifted harvest.',
    repliedAt: 'Today, 09:10 AM',
  },
  {
    id: 'FB-002',
    type: 'DELIVERY',
    authorName: 'Solomon Mengistu',
    authorRole: 'CUSTOMER',
    city: 'Bahir Dar',
    rating: 5,
    title: 'Punctual Lakefront Delivery',
    comment: 'Driver Girma Wolde arrived exactly on schedule at Kebele 04 and helped unload the heavy Niger seed oil jerrycans directly to our store.',
    targetEntityName: 'Bahir Dar Delivery Run TRP-1044',
    status: 'REVIEWED',
    sentiment: 'POSITIVE',
    createdAt: 'Yesterday, 04:30 PM',
  },
  {
    id: 'FB-003',
    type: 'PLATFORM',
    authorName: 'Hiwot Assefa',
    authorRole: 'CUSTOMER',
    city: 'Addis Ababa',
    rating: 4,
    title: 'Telebirr checkout was instant',
    comment: 'Loved the smooth checkout in Telebirr. Would appreciate SMS notification when the truck is 15 minutes away from Bole Atlas.',
    targetEntityName: 'Ardab Mobile Web Checkout',
    status: 'NEW',
    sentiment: 'POSITIVE',
    createdAt: 'Today, 07:15 AM',
  },
  {
    id: 'FB-004',
    type: 'SUPPLIER',
    authorName: 'Gondar Farmers Union',
    authorRole: 'SUPPLIER',
    city: 'Gondar',
    rating: 5,
    title: 'Seamless Wholesale Consignment Handover',
    comment: 'The Ardab logistics truck arrives on time with exact weighbridge scales. Payment reconciliation with Commercial Bank of Ethiopia was prompt.',
    targetEntityName: 'Ardab Logistics Hub Gondar',
    status: 'REVIEWED',
    sentiment: 'POSITIVE',
    createdAt: '2 days ago',
  },
  {
    id: 'FB-005',
    type: 'PRODUCT',
    authorName: 'Kassahun Bekele',
    authorRole: 'CUSTOMER',
    city: 'Gondar',
    rating: 3,
    title: 'Good butter but bucket lid was slightly loose',
    comment: 'The spiced clarified butter aroma is rich, but one tin lid had a minor trace of butter seepage on delivery. Please reinforce sealing tape.',
    targetEntityName: 'Traditional Spiced Clarified Butter - Kibe',
    status: 'FLAGGED',
    sentiment: 'NEUTRAL',
    createdAt: '3 days ago',
    adminReply: 'Noted with thanks Kassahun. We have mandated protective heat-shrink bands on all dairy buckets.',
    repliedAt: '2 days ago',
  },
];

