import { TranslationKey } from './en';

export const am: Record<TranslationKey, string> = {
  // Common
  'common.appName': 'አርዳብ ገበያ',
  'common.currency': 'ብር',
  'common.retry': 'እንደገና ሞክር',
  'common.loading': 'እየጫነ ነው...',
  'common.error': 'ስህተት ተፈጥሯል',
  'common.cancel': 'ሰርዝ',
  'common.confirm': 'አረጋግጥ',
  'common.save': 'አስቀምጥ',
  'common.back': 'ተመለስ',
  'common.close': 'ዝጋ',
  'common.done': 'ተጠናቀቀ',
  'common.seeAll': 'ሁሉንም እይ',
  'common.viewMore': 'ተጨማሪ ይመልከቱ',
  'common.explore': 'ያስሱ',
  'common.apply': 'ተግብር',
  'common.reset': 'ዳግም አስጀምር',
  'common.clear': 'አጽዳ',
  'common.edit': 'አስተካክል',
  'common.delete': 'አጥፋ',
  'common.remove': 'አስወግድ',
  'common.ok': 'እሺ',
  'common.yes': 'አዎ',
  'common.no': 'አይደለም',
  'common.share': 'አጋራ',
  'common.or': 'ወይም',
  'common.verified': 'የተረጋገጠ',
  'common.items': 'እቃዎች',
  'common.off': 'ቅናሽ',
  'common.free': 'ነፃ',

  // Navigation
  'nav.home': 'መነሻ',
  'nav.categories': 'ምድቦች',
  'nav.cart': 'ጋሪ',
  'nav.orders': 'ትዕዛዞች',
  'nav.profile': 'መገለጫ',
  'nav.wishlist': 'የምወዳቸው',
  'nav.notifications': 'ማሳወቂያዎች',
  'nav.support': 'ድጋፍ',
  'nav.search': 'ፈልግ',

  // Language Switcher
  'lang.selectorTitle': 'ቋንቋ ይምረጡ',
  'lang.selectorSubtitle': 'የመተግበሪያውን ቋንቋ ይምረጡ',
  'lang.english': 'English',
  'lang.amharic': 'አማርኛ',
  'lang.shortEn': 'EN',
  'lang.shortAm': 'አማ',

  // Home
  'home.searchPlaceholder': 'ምርቶችን ይፈልጉ...',
  'home.deliveryTo': 'የማድረሻ ቦታ',
  'home.heroTitle': 'ተጨማሪ ያግኙ። በብልሃት ይግዙ።',
  'home.heroSubtitle': 'በአርዳብ ገበያ የሚወዷቸውን ምርቶች ያግኙ — ትኩስ የሸቀጣሸቀጥ፣ የባህል አልባሳት እና የዕለት ተዕለት ፍጆታዎች በቀጥታ ወደ እርስዎ ይደርሳሉ።',
  'home.shopNow': 'አሁን ይግዙ',
  'home.exploreCategories': 'ምድቦችን ያስሱ',
  'home.trending': 'በአሁኑ ጊዜ ተወዳጅ',
  'home.trendingSubtitle': 'በዚህ ሳምንት በመላው ኢትዮጵያ በብዛት የተመረጡ ምርቶች',
  'home.specialOffers': 'ልዩ ቅናሾች',
  'home.specialOffersSubtitle': 'እስከ 30% የሚደርስ የተወሰነ ጊዜ ቅናሽ',
  'home.recommended': 'ለእርስዎ የተመረጡ',
  'home.recommendedSubtitle': 'ከተረጋገጡ ነጋዴዎች ለእርስዎ የተመረጡ ምርቶች',
  'home.popular': 'ተወዳጅ ምርቶች',
  'home.newArrivals': 'አዳዲስ ምርቶች',
  'home.recentlyViewed': 'በቅርብ የታዩ',
  'home.categories': 'ምድቦችን ያስሱ',
  'home.categoriesSubtitle': 'የተረጋገጡ ምርቶችን በምድብ ለይተው ይፈልጉ',
  'home.verifiedMarketplace': 'የተረጋገጠ የኢትዮጵያ ገበያ',
  'home.expressDelivery': 'ፈጣን የከተማ ማድረስ',
  'home.benefitsTitle': 'ለምን አርዳብ ገበያን ይመርጣሉ?',
  'home.benefit1Title': '100% የተረጋገጡ ነጋዴዎች',
  'home.benefit1Desc': 'ሁሉም ነጋዴዎች ማንነታቸውና ሕጋዊ የንግድ ፈቃዳቸው የተረጋገጠ ነው።',
  'home.benefit2Title': 'ፈጣን እና አስተማማኝ አቅርቦት',
  'home.benefit2Desc': 'የትዕዛዝዎን ሂደት በቀጥታ እየተከታተሉ በርዎ ድረስ በፍጥነት ይቀበሉ።',
  'home.benefit3Title': 'አስተማማኝ የሀገር ውስጥ ክፍያ',
  'home.benefit3Desc': 'በቴሌብር፣ በሲቢኢ ብር ወይም እቃው ሲደርስ በቀላሉ ይክፈሉ።',
  'home.ctaTitle': 'ግዢ ለመጀመር ዝግጁ ኖት?',
  'home.ctaSubtitle': 'በኢትዮጵያ ቀዳሚ በሆነው አስተማማኝ ዲጂታል ገበያ በሺዎች ከሚቆጠሩ እርካታ ደንበኞች ጋር ይቀላቀሉ።',
  'home.ctaButton': 'ሙሉውን ገበያ ያስሱ',

  // Search & Filter
  'search.title': 'ምርቶችን ይፈልጉ',
  'search.placeholder': 'ምርቶችን ይፈልጉ...',
  'search.recent': 'የቅርብ ፍለጋዎች',
  'search.popular': 'ተወዳጅ ፍለጋዎች',
  'search.clearRecent': 'የቅርብ ፍለጋን አጽዳ',
  'search.noResults': 'ምንም ምርት አልተገኘም',
  'search.noResultsSub': 'እባክዎ የቃላት አጻጻፍዎን ያረጋግጡ ወይም ሰፋ ያሉ የፍለጋ ቃላትን ይጠቀሙ።',
  'search.searchAgain': 'እንደገና ፈልግ',
  'search.clearSearch': 'ፍለጋውን አጽዳ',
  'search.filters': 'አጣራ',
  'search.sort': 'ደርድር',
  'search.sortBy': 'በዚህ ደርድር',
  'search.sort.popular': 'በጣም ተወዳጅ',
  'search.sort.priceLowHigh': 'ዋጋ፡ ከዝቅተኛ ወደ ከፍተኛ',
  'search.sort.priceHighLow': 'ዋጋ፡ ከከፍተኛ ወደ ዝቅተኛ',
  'search.sort.newest': 'አዳዲስ ምርቶች',
  'search.sort.rating': 'ከፍተኛ ደረጃ የተሰጣቸው',
  'search.priceRange': 'የዋጋ ክልል (ብር)',
  'search.category': 'ምድብ',
  'search.rating': 'ደረጃ',
  'search.applyFilters': 'አጣራን ተግብር',
  'search.resetFilters': 'አጣራን ዳግም አስጀምር',
  'search.resultsCount': '{count} ምርቶች ተገኝተዋል',

  // Categories
  'categories.title': 'ምድቦች',
  'categories.all': 'ሁሉም ምድቦች',
  'categories.subtitle': 'የተረጋገጡ የሸቀጥ እና የአገልግሎት ክፍሎችን ያስሱ',
  'categories.subcategories': 'ንዑስ ምድቦች',
  'categories.itemsCount': 'እቃዎች',
  'categories.viewAllIn': 'በ{category} ያሉትን ሁሉንም እይ',
  'categories.viewAllProducts': 'በዚህ ምድብ ያሉትን ሁሉንም ምርቶች ይመልከቱ',
  'categories.searchPlaceholder': 'ምድቦችን ይፈልጉ...',
  'categories.noResults': 'ምንም ምድቦች አልተገኙም',
  'categories.browseProducts': 'ሁሉንም ምርቶች ያስሱ',

  // Product Card & Details
  'product.title': 'የምርት ዝርዝር',
  'product.price': 'ዋጋ',
  'product.discount': 'ቅናሽ',
  'product.available': 'በመጋዘን አለ',
  'product.inStock': 'በመጋዘን አለ',
  'product.outOfStock': 'አልቋል',
  'product.addToCart': 'ወደ ጋሪ ጨምር',
  'product.buyNow': 'አሁን ይግዙ',
  'product.addedToCart': 'ወደ ጋሪ ተጨምሯል!',
  'product.addToWishlist': 'ወደ የምወዳቸው አስገባ',
  'product.removeFromWishlist': 'ከየምወዳቸው አውጣ',
  'product.addedToWishlist': 'ወደ የምወዳቸው ተቀምጧል!',
  'product.removedFromWishlist': 'ከየምወዳቸው ወጥቷል',
  'product.description': 'የምርት ማብራሪያ',
  'product.specifications': 'ዝርዝር መግለጫዎች',
  'product.seller': 'የሻጩ መረጃ',
  'product.verifiedSeller': 'የተረጋገጠ ነጋዴ',
  'product.rating': 'ደረጃ',
  'product.reviews': 'ግምገማዎች',
  'product.customerReviews': 'የደንበኞች ግምገማዎች',
  'product.writeReview': 'ግምገማ ጻፍ',
  'product.submitReview': 'ግምገማ አስገባ',
  'product.noReviewsYet': 'ለዚህ ምርት እስካሁን ምንም ግምገማ የለም',
  'product.averageRating': 'አማካይ ደረጃ',
  'product.sold': 'የተሸጠ',
  'product.origin': 'መገኛ ቦታ',
  'product.deliveryInfo': 'የአቅርቦት መረጃ',
  'product.fastDeliveryBadge': 'ፈጣን የከተማ አቅርቦት አለው',
  'product.relatedProducts': 'ተዛማጅ ምርቶች',
  'product.quantity': 'ብዛት',
  'product.selectOptions': 'አማራጮችን ይምረጡ',

  // Cart
  'cart.title': 'የእርስዎ ጋሪ',
  'cart.items': 'እቃዎች',
  'cart.empty': 'የእርስዎ ጋሪ ባዶ ነው',
  'cart.emptySub': 'እስካሁን ምንም አይነት እቃ ወደ ጋሪዎ አላስገቡም።',
  'cart.startShopping': 'ግዢ ይጀምሩ',
  'cart.continueShopping': 'ግዢዎን ይቀጥሉ',
  'cart.quantity': 'ብዛት',
  'cart.subtotal': 'ንዑስ ድምር',
  'cart.deliveryFee': 'የአቅርቦት ክፍያ',
  'cart.discount': 'ቅናሽ',
  'cart.total': 'አጠቃላይ ድምር',
  'cart.checkout': 'ወደ ክፍያ ይቀጥሉ',
  'cart.selectAll': 'ሁሉንም ምረጥ',
  'cart.remove': 'አስወግድ',
  'cart.itemRemoved': 'እቃው ከጋሪ ተወግዷል',
  'cart.freeDeliveryEligible': 'በጎንደር እና በአዲስ አበባ ነፃ የማድረስ ዕድል አለው',

  // Checkout
  'checkout.title': 'ክፍያ',
  'checkout.deliveryInfo': 'የአቅርቦት መረጃ',
  'checkout.deliveryAddress': 'የማድረሻ አድራሻ',
  'checkout.addNewAddress': '+ አዲስ አድራሻ አስገባ',
  'checkout.selectAddress': 'የማድረሻ አድራሻ ይምረጡ',
  'checkout.city': 'ከተማ',
  'checkout.phone': 'ስልክ ቁጥር',
  'checkout.recipientName': 'የተቀባይ ስም',
  'checkout.specificAddress': 'የሰፈር ወይም የቤት መለያ አድራሻ',
  'checkout.paymentMethod': 'የክፍያ ዘዴ',
  'checkout.paymentMethodSub': 'የሚፈልጉትን የክፍያ አማራጭ ይምረጡ',
  'checkout.cashOnDelivery': 'እቃው ሲደርስ የሚከፈል',
  'checkout.cashOnDeliveryDesc': 'እቃዎ በርዎ ላይ ሲደርስ በጥሬ ገንዘብ ይክፈሉ',
  'checkout.telebirr': 'ቴሌብር (Telebirr)',
  'checkout.telebirrDesc': 'በቴሌብር የሞባይል አካውንትዎ በፍጥነት ይክፈሉ',
  'checkout.cbeBirr': 'ሲቢኢ ብር (CBE Birr)',
  'checkout.cbeBirrDesc': 'በኢትዮጵያ ንግድ ባንክ ሲቢኢ ብር መተግበሪያ ይክፈሉ',
  'checkout.bankTransfer': 'ቀጥታ የባንክ ዝውውር',
  'checkout.bankTransferDesc': 'በሞባይል ባንኪንግ ወደ አርዳብ የተረጋገጠ ሂሳብ ያስተላልፉ',
  'checkout.orderSummary': 'የትዕዛዝ ማጠቃለያ',
  'checkout.confirmOrder': 'ትዕዛዝ አረጋግጥ',
  'checkout.placeOrder': 'ትዕዛዝ አጠናቅቅ',
  'checkout.orderSuccessful': 'ትዕዛዝዎ በተሳካ ሁኔታ ተላልፏል!',
  'checkout.orderSuccessfulSub': 'ትዕዛዝዎን ተቀብለናል፤ በነጋዴው እየተዘጋጀ ይገኛል።',
  'checkout.orderFailed': 'ትዕዛዙን ማጠናቀቅ አልተቻለም',
  'checkout.viewOrder': 'የትዕዛዝ ዝርዝር እይ',
  'checkout.trackOrder': 'የትዕዛዝ ሁኔታ ተከታተል',

  // Orders
  'orders.title': 'ትዕዛዞቼ',
  'orders.tabAll': 'ሁሉም',
  'orders.tabToPay': 'ክፍያ የሚጠብቅ',
  'orders.tabProcessing': 'በዝግጅት ላይ',
  'orders.tabShipping': 'በመንገድ ላይ',
  'orders.tabDelivered': 'የደረሰ',
  'orders.tabCancelled': 'የተሰረዘ',
  'orders.noOrders': 'እስካሁን ምንም ትዕዛዝ የለም',
  'orders.noOrdersSub': 'ትዕዛዝ ሲያዙ ሂደቱን በዚህ ገጽ መከታተል ይችላሉ።',
  'orders.orderNumber': 'የትዕዛዝ ቁጥር',
  'orders.orderDate': 'የትዕዛዝ ቀን',
  'orders.total': 'አጠቃላይ ድምር',
  'orders.trackOrder': 'ትዕዛዝ ተከታተል',
  'orders.viewDetails': 'ዝርዝር እይ',
  'orders.reorder': 'እንደገና እዘዝ',
  'orders.cancelOrder': 'ትዕዛዝ ሰርዝ',
  'orders.orderTimeline': 'የትዕዛዝ ሂደት',
  'orders.statusPending': 'ማረጋገጫ የሚጠብቅ',
  'orders.statusConfirmed': 'ተረጋግጧል',
  'orders.statusProcessing': 'በመጋዘን ዝግጅት ላይ',
  'orders.statusShipped': 'በማድረስ ሂደት ላይ',
  'orders.statusDelivered': 'ደርሷል',
  'orders.statusCancelled': 'ተሰርዟል',
  'orders.deliveryEstimate': 'የሚደርስበት ግምታዊ ጊዜ',
  'orders.driverContact': 'የአሽከርካሪ ስልክ',

  // Profile & Settings
  'profile.title': 'መገለጫ',
  'profile.sectionActivity': 'የገበያ እንቅስቃሴ',
  'profile.sectionPreferences': 'ምርጫዎች እና ደህንነት',
  'profile.sectionSupport': 'እርዳታ እና መረጃ',
  'profile.personalInfo': 'የግል መረጃ',
  'profile.myOrders': 'ትዕዛዞቼ',
  'profile.wishlist': 'የምወዳቸው',
  'profile.addresses': 'የተቀመጡ አድራሻዎች',
  'profile.security': 'ደህንነት እና ሚስጥራዊነት',
  'profile.changePassword': 'የይለፍ ቃል ቀይር',
  'profile.language': 'ቋንቋ / Language',
  'profile.notifications': 'ማሳወቂያዎች',
  'profile.support': 'እርዳታ እና ድጋፍ',
  'profile.about': 'ስለ አርዳብ ገበያ',
  'profile.aboutDesc1': 'አርዳብ ገበያ ደንበኞችን ከተረጋገጡ የኢትዮጵያ ገበሬዎች ማህበራት፣ የባህል አልባሳት ባለሙያዎች እና አስተማማኝ ነጋዴዎች ጋር በቀጥታ ያገናኛል።',
  'profile.aboutDesc2': 'በጎንደር እና በአዲስ አበባ ዋና መስሪያ ቤቱን ያደረገው አርዳብ ገበያ ጥራትን፣ ተመጣጣኝ ዋጋን፣ አስተማማኝ ክፍያን እና ፈጣን አቅርቦትን ያረጋግጣል።',
  'profile.version': 'ስሪት 1.0.0 (የኤክስፖ የሞባይል መተግበሪያ)',
  'profile.logout': 'ውጣ',
  'profile.logoutConfirm': 'እርግጠኛ ኖት ከመለያዎ መውጣት ይፈልጋሉ?',
  'profile.editProfile': 'መለያ አሻሽል',
  'profile.memberSince': 'አባል ከ',
  'profile.fullName': 'ሙሉ ስም',
  'profile.email': 'ኢሜይል አድራሻ',
  'profile.phone': 'ስልክ ቁጥር',
  'profile.city': 'ከተማ / መኖሪያ',
  'profile.saveProfile': 'መረጃ አስቀምጥ',
  'profile.selectLanguage': 'የመተግበሪያ ቋንቋ ይምረጡ',
  'profile.languageHint': 'ቋንቋ ሲቀይሩ በመተግበሪያው ውስጥ ያሉ ሁሉም ገጾች ወዲያውኑ ይቀየራሉ።',

  // Wishlist
  'wishlist.title': 'የምወዳቸው',
  'wishlist.empty': 'የምወዳቸው ዝርዝር ባዶ ነው',
  'wishlist.emptySub': 'በማንኛውም ምርት ላይ ያለውን የልብ ቅርጽ በመጫን በኋላ ላይ ለመግዛት የሚፈልጓቸውን እቃዎች ያስቀምጡ።',
  'wishlist.moveAllToCart': 'ሁሉንም ወደ ጋሪ አስገባ',

  // Authentication & Registration
  'auth.welcome': 'እንኳን ወደ አርዳብ ገበያ በደህና መጡ',
  'auth.welcomeSubtitle': 'የኢትዮጵያ አስተማማኝ የሸቀጣሸቀጥ፣ የባህል አልባሳት፣ ኤሌክትሮኒክስ እና አስፈላጊ የዕለት ተዕለት ፍጆታዎች መገበያያ።',
  'auth.getStarted': 'ይጀምሩ',
  'auth.signIn': 'ግባ',
  'auth.signUp': 'አዲስ መለያ ፍጠር',
  'auth.createAccountTitle': 'መለያዎን ይፍጠሩ',
  'auth.createAccountSubtitle': 'አርዳብ ገበያን ይቀላቀሉ እና መሸመት ይጀምሩ።',
  'auth.methodEmail': 'ኢሜይል',
  'auth.methodTelegram': 'ቴሌግራም',
  'auth.continueWithEmail': 'በኢሜይል ይቀጥሉ',
  'auth.continueWithTelegram': 'በቴሌግራም ይቀጥሉ',
  'auth.telegramPhone': 'የቴሌግራም ስልክ ቁጥር',
  'auth.telegramDesc': 'የማረጋገጫ ኮድ በአርዳብ የቴሌግራም ቦት በኩል ወደ ቴሌግራም መለያዎ ይላካል።',
  'auth.openTelegramBot': 'የአርዳብ ቴሌግራም ቦትን ክፈት',
  'auth.verificationCodeSent': 'የማረጋገጫ ኮድ ተልኳል',
  'auth.enterEmailOtp': 'ወደ ኢሜይልዎ የተላከውን ባለ 6-አሃዝ ኮድ ያስገቡ።',
  'auth.enterTelegramOtp': 'የማረጋገጫ ኮድዎ ወደ ቴሌግራም መለያዎ ተልኳል።',
  'auth.createPasswordTitle': 'የይለፍ ቃልዎን ይፍጠሩ',
  'auth.createPasswordSubtitle': 'ለአዲሱ የአርዳብ ገበያ መለያዎ አስተማማኝ የይለፍ ቃል ይምረጡ።',
  'auth.welcomeBack': 'እንኳን ደህና መጡ',
  'auth.welcomeBackUser': 'እንኳን ደህና መጡ 👋',
  'auth.useThisAccount': 'በዚህ መለያ ቀጥል',
  'auth.switchAccount': 'መለያ ቀይር',
  'auth.useAnotherAccount': 'ሌላ መለያ ይጠቀሙ',
  'auth.useSavedAccount': 'የተቀመጠውን መለያ ይጠቀሙ',
  'auth.confirmSignOut': 'እርግጠኛ ነዎት ከመለያዎ መውጣት ይፈልጋሉ?',
  'auth.signOutConfirmTitle': 'መውጣት',
  'auth.cancel': 'ይቅር',
  'auth.enterNewPassword': 'አዲስ የይለፍ ቃል ያስገቡ',
  'auth.resetToken': 'የማስተካከያ ኮድ',
  'auth.newPassword': 'አዲስ የይለፍ ቃል',
  'auth.passwordResetSuccess': 'የይለፍ ቃልዎ በሚገባ ተቀይሯል። አሁን መግባት ይችላሉ።',
  'auth.changePhone': 'ስልክ ቁጥር ቀይር',
  'auth.changeEmail': 'ኢሜይል ቀይር',
  'auth.passwordStrength': 'የይለፍ ቃል ጥንካሬ',
  'auth.weak': 'ደካማ',
  'auth.medium': 'መካከለኛ',
  'auth.strong': 'ጠንካራ',
  'auth.showPassword': 'አሳይ',
  'auth.hidePassword': 'ደብቅ',
  'auth.accountExists': 'መለያ አስቀድሞ አለ። እባክዎ ይግቡ።',
  'auth.loginDesc': 'ትዕዛዞችዎን፣ ጋሪዎን እና ልዩ ቅናሾችን ለማግኘት ይግቡ።',
  'auth.autoSignIn': 'ወደ መለያዎ በማስገባት ላይ...',
  'auth.login': 'ግባ',
  'auth.email': 'ኢሜይል አድራሻ',
  'auth.phone': 'ስልክ ቁጥር',
  'auth.emailOrPhone': 'ኢሜይል ወይም ስልክ ቁጥር',
  'auth.password': 'የይለፍ ቃል',
  'auth.confirmPassword': 'የይለፍ ቃል አረጋግጥ',
  'auth.createPassword': 'የይለፍ ቃል ፍጠር',
  'auth.fullName': 'ሙሉ ስም',
  'auth.city': 'ከተማ / መኖሪያ',
  'auth.selectCity': 'ከተማዎን ይምረጡ',
  'auth.forgotPassword': 'የይለፍ ቃል ረሱ?',
  'auth.continue': 'ቀጥል',
  'auth.submit': 'አስገባ',
  'auth.alreadyHaveAccount': 'ቀደም ሲል መለያ አለዎት? ግባ',
  'auth.dontHaveAccount': 'መለያ የለዎትም? አዲስ መለያ ፍጠር',
  'auth.verifyEmail': 'ኢሜይል አረጋግጥ',
  'auth.verification': 'የኢሜይል ማረጋገጫ',
  'auth.verifyOtpDesc': 'መለያዎን ለማረጋገጥ ወደ ኢሜይልዎ የተላከውን ባለ 6 አሃዝ ኮድ ያስገቡ።',
  'auth.verify': 'አረጋግጥ እና ቀጥል',
  'auth.resendCode': 'ኮዱን እንደገና ላክ',
  'auth.codeResent': 'የማረጋገጫ ኮድ በተሳካ ሁኔታ እንደገና ተልኳል',
  'auth.otpExpired': 'ይህ የማረጋገጫ ኮድ ጊዜው አልፎበታል:: እባክዎ አዲስ ኮድ ይጠይቁ::',
  'auth.invalidOtp': 'የተሳሳተ የማረጋገጫ ኮድ:: እባክዎ እንደገና ይሞክሩ::',
  'auth.resetPassword': 'የይለፍ ቃል ቀይር',
  'auth.resetPasswordDesc': 'መመሪያዎችን ለመቀበል የተመዘገቡበትን ኢሜይል ወይም ስልክ ያስገቡ።',
  'auth.sendResetLink': 'የማስተካከያ ኮድ ላክ',
  'auth.accountCreated': 'መለያዎ በተሳካ ሁኔታ ተፈጥሯል!',
  'auth.verificationSent': 'የማረጋገጫ ኢሜይል ተልኳል',
  'auth.logout': 'ውጣ',

  // Customer Support
  'support.title': 'የደንበኞች ድጋፍ',
  'support.contactSupport': 'ድጋፍ ሰጪን ያነጋግሩ',
  'support.callUs': 'የድጋፍ መስመር ደውል',
  'support.emailUs': 'የደንበኞች አገልግሎት ኢሜይል',
  'support.telegramUs': 'የቴሌግራም ድጋፍ',
  'support.subject': 'ርዕስ',
  'support.subjectPlaceholder': 'በምን ጉዳይ እርዳታ ይፈልጋሉ?',
  'support.message': 'መልእክት',
  'support.messagePlaceholder': 'ጉዳይዎን ወይም ጥያቄዎን በዝርዝር ያብራሩ...',
  'support.send': 'መልእክት ላክ',
  'support.messageSent': 'መልእክትዎ በተሳካ ሁኔታ ተልኳል',
  'support.messageSentDesc': 'የድጋፍ ቡድናችን በ24 ሰዓት ውስጥ ምላሽ ይሰጥዎታል።',
  'support.faq': 'ተደጋግመው የሚጠየቁ ጥያቄዎች',
  'support.hours': 'የስራ ሰዓት፡ ከሰኞ - ቅዳሜ ከጠዋቱ 2:00 - ማታ 2:00',

  // Validation Messages
  'validation.required': 'ይህ ቦታ መሞላት አለበት',
  'validation.emailRequired': 'ኢሜይል ያስፈልጋል',
  'validation.invalidEmail': 'እባክዎ ትክክለኛ የኢሜይል አድራሻ ያስገቡ',
  'validation.phoneRequired': 'ስልክ ቁጥር ያስፈልጋል',
  'validation.invalidPhone': 'እባክዎ ትክክለኛ የኢትዮጵያ ስልክ ቁጥር ያስገቡ (ለምሳሌ 09... ወይም +251...)',
  'validation.passwordRequired': 'የይለፍ ቃል ያስፈልጋል',
  'validation.passwordLength': 'የይለፍ ቃሉ ቢያንስ 8 ፊደሎች ወይም ምልክቶች ሊኖሩት ይገባል',
  'validation.passwordMismatch': 'የይለፍ ቃሎቹ አይመሳሰሉም',
  'validation.fullNameRequired': 'ሙሉ ስም ያስፈልጋል',
  'validation.cityRequired': 'እባክዎ ከተማዎን ይምረጡ',
  'validation.addressRequired': 'የማድረሻ አድራሻ ያስፈልጋል',

  // Errors & API Handling
  'errors.general': 'ስህተት ተፈጥሯል። እባክዎ እንደገና ይሞክሩ።',
  'errors.network': 'የኔትወርክ ግንኙነት ችግር ተፈጥሯል። እባክዎ ኢንተርኔትዎን ያረጋግጡ።',
  'errors.server': 'የሰርቨር ችግር አጋጥሟል። መሐንዲሶቻችን እየተመለከቱት ነው።',
  'errors.unauthorized': 'የቆይታ ጊዜዎ አልቋል። እባክዎ እንደገና ይግቡ።',
  'errors.invalidCredentials': 'የተሳሳተ ኢሜይል/ስልክ ወይም የይለፍ ቃል ነው። እባክዎ እንደገና ይሞክሩ።',
  'errors.productNotFound': 'ምርቱ አልተገኘም ወይም በአሁኑ ጊዜ የለም።',
  'errors.orderFailed': 'ትዕዛዙን ማጠናቀቅ አልተቻለም። እባክዎ እንደገና ይሞክሩ ወይም ሌላ የክፍያ ዘዴ ይምረጡ።',
  'errors.paymentFailed': 'ክፍያው አልተሳካም። እባክዎ እንደገና ይሞክሩ።',
  'errors.tryAgain': 'እባክዎ እንደገና ይሞክሩ',

  // Success States
  'success.title': 'ተሳክቷል',
  'success.saved': 'በተሳካ ሁኔታ ተቀምጧል',
  'success.updated': 'በተሳካ ሁኔታ ተሻሽሏል',
  'success.addedToCart': 'ወደ ጋሪ ተጨምሯል',
  'success.removedFromCart': 'ከጋሪ ተወግዷል',
  'success.addedToWishlist': 'ወደ የምወዳቸው ተቀምጧል',
  'success.removedFromWishlist': 'ከየምወዳቸው ተወግዷል',
  'success.profileUpdated': 'መገለጫዎ በተሳካ ሁኔታ ተሻሽሏል',
  'success.passwordChanged': 'የይለፍ ቃልዎ በተሳካ ሁኔታ ተቀይሯል',

  // Empty States
  'empty.products': 'ምንም ምርት አልተገኘም',
  'empty.orders': 'ምንም ትዕዛዝ የለም',
  'empty.cart': 'የእርስዎ ጋሪ ባዶ ነው',
  'empty.wishlist': 'የምወዳቸው ዝርዝር ባዶ ነው',
  'empty.reviews': 'ምንም ግምገማ አልተሰጠም',
  'empty.notifications': 'ምንም ማሳወቂያ የለም',

  // Loading States
  'loading.general': 'እየጫነ ነው...',
  'loading.products': 'ምርቶችን እየጫነ ነው...',
  'loading.categories': 'ምድቦችን እየጫነ ነው...',
  'loading.processing': 'እየሰራ ነው...',
  'loading.pleaseWait': 'እባክዎ ይጠብቁ...',
};
