export const en = {
  // Common
  'common.appName': 'Ardab Market',
  'common.currency': 'ETB',
  'common.retry': 'Try Again',
  'common.loading': 'Loading...',
  'common.error': 'Something went wrong',
  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.save': 'Save Changes',
  'common.back': 'Back',
  'common.close': 'Close',
  'common.done': 'Done',
  'common.seeAll': 'See All',
  'common.viewMore': 'View More',
  'common.explore': 'Explore',
  'common.apply': 'Apply',
  'common.reset': 'Reset',
  'common.clear': 'Clear',
  'common.edit': 'Edit',
  'common.delete': 'Delete',
  'common.remove': 'Remove',
  'common.ok': 'OK',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.share': 'Share',
  'common.or': 'or',
  'common.verified': 'Verified',
  'common.items': 'items',
  'common.off': 'OFF',
  'common.free': 'FREE',

  // Navigation
  'nav.home': 'Home',
  'nav.categories': 'Categories',
  'nav.cart': 'Cart',
  'nav.orders': 'Orders',
  'nav.profile': 'Profile',
  'nav.wishlist': 'Wishlist',
  'nav.notifications': 'Notifications',
  'nav.support': 'Support',
  'nav.search': 'Search',

  // Language Switcher
  'lang.selectorTitle': 'Select Language',
  'lang.selectorSubtitle': 'Choose your preferred display language',
  'lang.english': 'English',
  'lang.amharic': 'አማርኛ',
  'lang.shortEn': 'EN',
  'lang.shortAm': 'አማ',

  // Home
  'home.searchPlaceholder': 'Search products, brands, groceries...',
  'home.deliveryTo': 'Deliver to',
  'home.heroTitle': 'Discover More. Shop Smarter.',
  'home.heroSubtitle': 'Find products you love on Ardab Market — authentic Ethiopian groceries, fashion, and everyday essentials delivered directly to you.',
  'home.shopNow': 'Shop Now',
  'home.exploreCategories': 'Explore Categories',
  'home.trending': 'Trending Now',
  'home.trendingSubtitle': 'Most demanded products this week across Ethiopia',
  'home.specialOffers': 'Special Offers',
  'home.specialOffersSubtitle': 'Limited-time discounts up to 30% off',
  'home.recommended': 'Recommended For You',
  'home.recommendedSubtitle': 'Handpicked based on popular verified sellers',
  'home.popular': 'Popular Products',
  'home.newArrivals': 'New Arrivals',
  'home.recentlyViewed': 'Recently Viewed',
  'home.categories': 'Explore Categories',
  'home.categoriesSubtitle': 'Browse verified products by departmental category',
  'home.verifiedMarketplace': 'Verified Ethiopian Marketplace',
  'home.expressDelivery': 'Fast Local Delivery',
  'home.benefitsTitle': 'Why Choose Ardab Market?',
  'home.benefit1Title': '100% Verified Sellers',
  'home.benefit1Desc': 'All merchants undergo strict local identity and license verification.',
  'home.benefit2Title': 'Fast & Secure Delivery',
  'home.benefit2Desc': 'Direct order tracking and swift delivery right to your door.',
  'home.benefit3Title': 'Trusted Local Payments',
  'home.benefit3Desc': 'Pay easily via Telebirr, CBE Birr, or Cash on Delivery.',
  'home.ctaTitle': 'Ready to Start Shopping?',
  'home.ctaSubtitle': 'Join thousands of satisfied shoppers enjoying Ethiopia’s premier digital marketplace.',
  'home.ctaButton': 'Explore Full Marketplace',

  // Search & Filter
  'search.title': 'Search Products',
  'search.placeholder': 'Search products, brands, sellers...',
  'search.recent': 'Recent Searches',
  'search.popular': 'Popular Searches',
  'search.clearRecent': 'Clear Recent',
  'search.noResults': 'No products found',
  'search.noResultsSub': 'Try checking your spelling or using more general search terms.',
  'search.searchAgain': 'Search Again',
  'search.clearSearch': 'Clear Search',
  'search.filters': 'Filters',
  'search.sort': 'Sort',
  'search.sortBy': 'Sort By',
  'search.sort.popular': 'Most Popular',
  'search.sort.priceLowHigh': 'Price: Low to High',
  'search.sort.priceHighLow': 'Price: High to Low',
  'search.sort.newest': 'Newest Arrivals',
  'search.sort.rating': 'Highest Rated',
  'search.priceRange': 'Price Range (ETB)',
  'search.category': 'Category',
  'search.rating': 'Rating',
  'search.applyFilters': 'Apply Filters',
  'search.resetFilters': 'Reset Filters',
  'search.resultsCount': 'Found {count} products',

  // Categories
  'categories.title': 'Categories',
  'categories.all': 'All Categories',
  'categories.subtitle': 'Browse verified departments across Ethiopia',
  'categories.subcategories': 'Subcategories',
  'categories.itemsCount': 'items',
  'categories.viewAllIn': 'View all in {category}',
  'categories.viewAllProducts': 'View all products in this category',
  'categories.searchPlaceholder': 'Search categories...',
  'categories.noResults': 'No categories found',
  'categories.browseProducts': 'Browse all products',

  // Product Card & Details
  'product.title': 'Product Details',
  'product.price': 'Price',
  'product.discount': 'Discount',
  'product.available': 'In Stock',
  'product.inStock': 'In Stock',
  'product.outOfStock': 'Out of Stock',
  'product.addToCart': 'Add to Cart',
  'product.buyNow': 'Buy Now',
  'product.addedToCart': 'Added to your cart!',
  'product.addToWishlist': 'Add to Wishlist',
  'product.removeFromWishlist': 'Remove from Wishlist',
  'product.addedToWishlist': 'Added to wishlist!',
  'product.removedFromWishlist': 'Removed from wishlist',
  'product.description': 'Product Description',
  'product.specifications': 'Specifications',
  'product.seller': 'Seller Information',
  'product.verifiedSeller': 'Verified Merchant',
  'product.rating': 'Rating',
  'product.reviews': 'Reviews',
  'product.customerReviews': 'Customer Reviews',
  'product.writeReview': 'Write a Review',
  'product.submitReview': 'Submit Review',
  'product.noReviewsYet': 'No reviews yet for this product',
  'product.averageRating': 'Average Rating',
  'product.sold': 'sold',
  'product.origin': 'Origin',
  'product.deliveryInfo': 'Delivery Information',
  'product.fastDeliveryBadge': 'Fast City Delivery Available',
  'product.relatedProducts': 'Related Products',
  'product.quantity': 'Quantity',
  'product.selectOptions': 'Select Options',

  // Cart
  'cart.title': 'Your Cart',
  'cart.items': 'items',
  'cart.empty': 'Your cart is empty',
  'cart.emptySub': 'Looks like you have not added anything to your cart yet.',
  'cart.startShopping': 'Start Shopping',
  'cart.continueShopping': 'Continue Shopping',
  'cart.quantity': 'Quantity',
  'cart.subtotal': 'Subtotal',
  'cart.deliveryFee': 'Delivery Fee',
  'cart.discount': 'Discount',
  'cart.total': 'Total',
  'cart.checkout': 'Proceed to Checkout',
  'cart.selectAll': 'Select All',
  'cart.remove': 'Remove',
  'cart.itemRemoved': 'Item removed from cart',
  'cart.freeDeliveryEligible': 'Eligible for Free Delivery in Gondar & Addis Ababa',

  // Checkout
  'checkout.title': 'Checkout',
  'checkout.deliveryInfo': 'Delivery Information',
  'checkout.deliveryAddress': 'Delivery Address',
  'checkout.addNewAddress': '+ Add New Address',
  'checkout.selectAddress': 'Select Delivery Address',
  'checkout.city': 'City',
  'checkout.phone': 'Phone Number',
  'checkout.recipientName': 'Recipient Name',
  'checkout.specificAddress': 'Specific Address / Neighborhood',
  'checkout.paymentMethod': 'Payment Method',
  'checkout.paymentMethodSub': 'Choose your preferred payment method',
  'checkout.cashOnDelivery': 'Cash on Delivery (COD)',
  'checkout.cashOnDeliveryDesc': 'Pay in cash when your package is delivered to your door',
  'checkout.telebirr': 'Telebirr',
  'checkout.telebirrDesc': 'Pay instantly with your Telebirr mobile wallet',
  'checkout.cbeBirr': 'CBE Birr',
  'checkout.cbeBirrDesc': 'Pay via Commercial Bank of Ethiopia CBE Birr app',
  'checkout.bankTransfer': 'Direct Bank Transfer',
  'checkout.bankTransferDesc': 'Transfer via mobile banking to Ardab verified account',
  'checkout.orderSummary': 'Order Summary',
  'checkout.confirmOrder': 'Confirm Order',
  'checkout.placeOrder': 'Place Order',
  'checkout.orderSuccessful': 'Order Placed Successfully!',
  'checkout.orderSuccessfulSub': 'Your order has been received and is being prepared by the merchant.',
  'checkout.orderFailed': 'Order Placement Failed',
  'checkout.viewOrder': 'View Order Details',
  'checkout.trackOrder': 'Track Order Status',

  // Orders
  'orders.title': 'My Orders',
  'orders.tabAll': 'All',
  'orders.tabToPay': 'To Pay',
  'orders.tabProcessing': 'Processing',
  'orders.tabShipping': 'Shipping',
  'orders.tabDelivered': 'Delivered',
  'orders.tabCancelled': 'Cancelled',
  'orders.noOrders': 'No orders yet',
  'orders.noOrdersSub': 'When you place an order, you can track its progress here.',
  'orders.orderNumber': 'Order Number',
  'orders.orderDate': 'Order Date',
  'orders.total': 'Total',
  'orders.trackOrder': 'Track Order',
  'orders.viewDetails': 'View Details',
  'orders.reorder': 'Reorder',
  'orders.cancelOrder': 'Cancel Order',
  'orders.orderTimeline': 'Order Timeline',
  'orders.statusPending': 'Pending Confirmation',
  'orders.statusConfirmed': 'Confirmed',
  'orders.statusProcessing': 'Processing in Warehouse',
  'orders.statusShipped': 'Out for Delivery',
  'orders.statusDelivered': 'Delivered',
  'orders.statusCancelled': 'Cancelled',
  'orders.deliveryEstimate': 'Estimated Delivery',
  'orders.driverContact': 'Delivery Driver Contact',

  // Profile & Settings
  'profile.title': 'Profile',
  'profile.sectionActivity': 'Marketplace Activity',
  'profile.sectionPreferences': 'Preferences & Security',
  'profile.sectionSupport': 'Support & Information',
  'profile.personalInfo': 'Personal Information',
  'profile.myOrders': 'My Orders',
  'profile.wishlist': 'Wishlist',
  'profile.addresses': 'Saved Addresses',
  'profile.security': 'Security & Privacy',
  'profile.changePassword': 'Change Password',
  'profile.language': 'Language / ቋንቋ',
  'profile.notifications': 'Notifications',
  'profile.support': 'Help & Support',
  'profile.about': 'About Ardab Market',
  'profile.aboutDesc1': 'Ardab Market connects consumers directly with verified Ethiopian agricultural unions, traditional master weavers, organic spice processors, and trusted merchants.',
  'profile.aboutDesc2': 'Headquartered in Gondar and Addis Ababa, we guarantee authentic quality, fair farmer prices, safe escrow payments, and rapid local courier delivery.',
  'profile.version': 'Version 1.0.0 (Expo Mobile Platform)',
  'profile.logout': 'Sign Out',
  'profile.logoutConfirm': 'Are you sure you want to sign out?',
  'profile.editProfile': 'Edit Profile',
  'profile.memberSince': 'Member since',
  'profile.fullName': 'Full Name',
  'profile.email': 'Email Address',
  'profile.phone': 'Phone Number',
  'profile.city': 'City / Location',
  'profile.saveProfile': 'Save Profile',
  'profile.selectLanguage': 'Select Application Language',
  'profile.languageHint': 'Changing language updates the interface immediately across all screens.',

  // Wishlist
  'wishlist.title': 'Wishlist',
  'wishlist.empty': 'Your wishlist is empty',
  'wishlist.emptySub': 'Save items you want to buy later by tapping the heart icon on any product.',
  'wishlist.moveAllToCart': 'Move All to Cart',

  // Authentication & Registration
  'auth.welcome': 'Welcome to Ardab Market',
  'auth.welcomeSubtitle': 'Ethiopia’s verified marketplace for authentic groceries, fashion, electronics, and local essentials.',
  'auth.getStarted': 'Get Started',
  'auth.signIn': 'Sign In',
  'auth.signUp': 'Create Account',
  'auth.createAccountTitle': 'Create Your Account',
  'auth.createAccountSubtitle': 'Join Ardab Market and start shopping.',
  'auth.methodEmail': 'Email',
  'auth.methodTelegram': 'Telegram',
  'auth.continueWithEmail': 'Continue with Email',
  'auth.continueWithTelegram': 'Continue with Telegram',
  'auth.telegramPhone': 'Telegram Phone Number',
  'auth.telegramDesc': 'An OTP will be sent to your Telegram account via Ardab Telegram Bot.',
  'auth.openTelegramBot': 'Open Telegram Bot',
  'auth.verificationCodeSent': 'Verification code sent',
  'auth.enterEmailOtp': 'Enter the 6-digit code sent to your email.',
  'auth.enterTelegramOtp': 'Your verification code has been sent to your Telegram account.',
  'auth.createPasswordTitle': 'Create Your Password',
  'auth.createPasswordSubtitle': 'Choose a secure password for your new Ardab Market account.',
  'auth.welcomeBack': 'Welcome Back',
  'auth.welcomeBackUser': 'Welcome back 👋',
  'auth.useThisAccount': 'Continue with this account',
  'auth.switchAccount': 'Switch account',
  'auth.useAnotherAccount': 'Use another account',
  'auth.useSavedAccount': 'Use saved account',
  'auth.confirmSignOut': 'Are you sure you want to sign out?',
  'auth.signOutConfirmTitle': 'Sign Out',
  'auth.cancel': 'Cancel',
  'auth.enterNewPassword': 'Enter New Password',
  'auth.resetToken': 'Reset Code / Token',
  'auth.newPassword': 'New Password',
  'auth.passwordResetSuccess': 'Password reset successfully! Please sign in.',
  'auth.changePhone': 'Change Phone Number',
  'auth.changeEmail': 'Change Email',
  'auth.passwordStrength': 'Password strength',
  'auth.weak': 'Weak',
  'auth.medium': 'Medium',
  'auth.strong': 'Strong',
  'auth.showPassword': 'Show',
  'auth.hidePassword': 'Hide',
  'auth.accountExists': 'An account already exists. Please sign in.',
  'auth.loginDesc': 'Sign in to access your orders, cart, and exclusive deals.',
  'auth.autoSignIn': 'Signing you in...',
  'auth.login': 'Login',
  'auth.email': 'Email Address',
  'auth.phone': 'Phone Number',
  'auth.emailOrPhone': 'Email or Phone Number',
  'auth.password': 'Password',
  'auth.confirmPassword': 'Confirm Password',
  'auth.createPassword': 'Create Password',
  'auth.fullName': 'Full Name',
  'auth.city': 'City / Location',
  'auth.selectCity': 'Select your city',
  'auth.forgotPassword': 'Forgot Password?',
  'auth.continue': 'Continue',
  'auth.submit': 'Submit',
  'auth.alreadyHaveAccount': 'Already have an account? Sign In',
  'auth.dontHaveAccount': 'Don’t have an account? Sign Up',
  'auth.verifyEmail': 'Verify Email',
  'auth.verification': 'Email Verification',
  'auth.verifyOtpDesc': 'Enter the 6-digit code sent to your email to verify your account.',
  'auth.verify': 'Verify & Continue',
  'auth.resendCode': 'Resend Code',
  'auth.codeResent': 'Verification code resent successfully',
  'auth.otpExpired': 'This verification code has expired. Please request a new code.',
  'auth.invalidOtp': 'Invalid verification code. Please check and try again.',
  'auth.resetPassword': 'Reset Password',
  'auth.resetPasswordDesc': 'Enter your registered email or phone to receive instructions.',
  'auth.sendResetLink': 'Send Reset Code',
  'auth.accountCreated': 'Account created successfully!',
  'auth.verificationSent': 'Verification email sent',
  'auth.logout': 'Logout',

  // Customer Support
  'support.title': 'Customer Support',
  'support.contactSupport': 'Contact Support',
  'support.callUs': 'Call Support Line',
  'support.emailUs': 'Email Customer Care',
  'support.telegramUs': 'Telegram Support',
  'support.subject': 'Subject',
  'support.subjectPlaceholder': 'What do you need help with?',
  'support.message': 'Message',
  'support.messagePlaceholder': 'Describe your issue or question in detail...',
  'support.send': 'Send Message',
  'support.messageSent': 'Message Sent Successfully',
  'support.messageSentDesc': 'Our support team will respond within 24 hours.',
  'support.faq': 'Frequently Asked Questions',
  'support.hours': 'Support Hours: Mon - Sat 8:00 AM - 8:00 PM',

  // Validation Messages
  'validation.required': 'This field is required',
  'validation.emailRequired': 'Email is required',
  'validation.invalidEmail': 'Please enter a valid email address',
  'validation.phoneRequired': 'Phone number is required',
  'validation.invalidPhone': 'Please enter a valid Ethiopian phone number (e.g. 09... or +251...)',
  'validation.passwordRequired': 'Password is required',
  'validation.passwordLength': 'Password must be at least 8 characters',
  'validation.passwordMismatch': 'Passwords do not match',
  'validation.fullNameRequired': 'Full name is required',
  'validation.cityRequired': 'Please select your city',
  'validation.addressRequired': 'Delivery address is required',

  // Errors & API Handling
  'errors.general': 'Something went wrong. Please try again.',
  'errors.network': 'Network error. Please check your internet connection.',
  'errors.server': 'Server error. Our engineers are looking into it.',
  'errors.unauthorized': 'Session expired. Please sign in again.',
  'errors.invalidCredentials': 'Incorrect email/phone or password. Please try again.',
  'errors.productNotFound': 'Product not found or currently unavailable.',
  'errors.orderFailed': 'Unable to complete order. Please try again or choose another payment method.',
  'errors.paymentFailed': 'Payment transaction failed. Please retry.',
  'errors.tryAgain': 'Please try again',

  // Success States
  'success.title': 'Success',
  'success.saved': 'Saved successfully',
  'success.updated': 'Updated successfully',
  'success.addedToCart': 'Added to cart',
  'success.removedFromCart': 'Removed from cart',
  'success.addedToWishlist': 'Added to wishlist',
  'success.removedFromWishlist': 'Removed from wishlist',
  'success.profileUpdated': 'Profile updated successfully',
  'success.passwordChanged': 'Password changed successfully',

  // Empty States
  'empty.products': 'No products found',
  'empty.orders': 'No orders yet',
  'empty.cart': 'Your cart is empty',
  'empty.wishlist': 'Your wishlist is empty',
  'empty.reviews': 'No reviews yet',
  'empty.notifications': 'No notifications yet',

  // Loading States
  'loading.general': 'Loading...',
  'loading.products': 'Loading products...',
  'loading.categories': 'Loading categories...',
  'loading.processing': 'Processing...',
  'loading.pleaseWait': 'Please wait...',
};

export type TranslationKey = keyof typeof en;
