import { Category, Product, Order, UserProfile, NotificationItem, SupportTicket } from '@/types';

export const CITIES = [
  'Addis Ababa',
  'Gondar',
  'Hawassa',
  'Bahir Dar',
  'Dire Dawa',
  'Mekelle',
  'Adama',
  'Jimma',
  'Dessie',
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-groceries',
    name: 'Groceries & Foods',
    nameAmharic: 'የሸቀጣሸቀጥ እና የምግብ እቃዎች',
    slug: 'groceries-foods',
    icon: 'nutrition-outline',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    productCount: 142,
    featured: true,
    subcategories: [
      { id: 'sub-teff-grains', name: 'Teff & Grains', nameAmharic: 'ጤፍ እና እህሎች', productCount: 45 },
      { id: 'sub-coffee-tea', name: 'Ethiopian Coffee & Tea', nameAmharic: 'ቡና እና ሻይ', productCount: 38 },
      { id: 'sub-spices', name: 'Spices & Berbere', nameAmharic: 'ቅመማ ቅመም እና በርበሬ', productCount: 32 },
      { id: 'sub-oil-honey', name: 'Honey & Oils', nameAmharic: 'ማር እና ዘይት', productCount: 27 },
    ],
  },
  {
    id: 'cat-fashion',
    name: 'Traditional & Fashion',
    nameAmharic: 'ባህላዊ እና ዘመናዊ አልባሳት',
    slug: 'traditional-fashion',
    icon: 'shirt-outline',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=400&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
    productCount: 88,
    featured: true,
    subcategories: [
      { id: 'sub-habesha-kemis', name: 'Habesha Kemis', nameAmharic: 'የሀበሻ ቀሚስ', productCount: 34 },
      { id: 'sub-mens-traditional', name: 'Men’s Traditional', nameAmharic: 'የወንዶች ባህላዊ ልብስ', productCount: 20 },
      { id: 'sub-scarves-netela', name: 'Netela & Gabi', nameAmharic: 'ነጠላ እና ጋቢ', productCount: 18 },
      { id: 'sub-shoes-accessories', name: 'Leather Goods & Shoes', nameAmharic: 'የቆዳ ጫማና እቃዎች', productCount: 16 },
    ],
  },
  {
    id: 'cat-electronics',
    name: 'Electronics & Power',
    nameAmharic: 'ኤሌክትሮኒክስ እና የኃይል እቃዎች',
    slug: 'electronics-power',
    icon: 'hardware-chip-outline',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=400&q=80',
    productCount: 96,
    featured: true,
    subcategories: [
      { id: 'sub-solar-power', name: 'Solar & Power Banks', nameAmharic: 'የፀሐይ ኃይል እና ፓወር ባንክ', productCount: 28 },
      { id: 'sub-phones-accessories', name: 'Phones & Accessories', nameAmharic: 'ስልኮች እና እቃዎች', productCount: 42 },
      { id: 'sub-audio-gadgets', name: 'Audio & Speakers', nameAmharic: 'ድምጽ ማጉያ እና ጆሮ ማዳመጫ', productCount: 26 },
    ],
  },
  {
    id: 'cat-home-kitchen',
    name: 'Home & Kitchen',
    nameAmharic: 'የቤት እና ወጥ ቤት እቃዎች',
    slug: 'home-kitchen',
    icon: 'home-outline',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=400&q=80',
    productCount: 75,
    featured: true,
    subcategories: [
      { id: 'sub-mitad-appliances', name: 'Electric Mitad & Stoves', nameAmharic: 'የኤሌክትሪክ ምጣድ', productCount: 19 },
      { id: 'sub-coffee-sets', name: 'Jebena & Sini Sets', nameAmharic: 'ጀበና እና ሲኒ', productCount: 24 },
      { id: 'sub-cookware', name: 'Cookware & Utensils', nameAmharic: 'የወጥ ቤት መገልገያዎች', productCount: 32 },
    ],
  },
  {
    id: 'cat-beauty-health',
    name: 'Health & Beauty',
    nameAmharic: 'ጤና እና ውበት',
    slug: 'health-beauty',
    icon: 'sparkles-outline',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=400&q=80',
    productCount: 64,
    featured: false,
    subcategories: [
      { id: 'sub-skincare-natural', name: 'Natural Oils & Soaps', nameAmharic: 'ተፈጥሯዊ ዘይቶች እና ሳሙና', productCount: 31 },
      { id: 'sub-herbal-supplements', name: 'Herbal Remedies', nameAmharic: 'የባህል መድኃኒቶች', productCount: 33 },
    ],
  },
  {
    id: 'cat-agriculture',
    name: 'Agriculture & Bulk',
    nameAmharic: 'ግብርና እና የጅምላ እቃዎች',
    slug: 'agriculture-bulk',
    icon: 'leaf-outline',
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=400&q=80',
    productCount: 52,
    featured: false,
    subcategories: [
      { id: 'sub-grain-sacks', name: 'Grain Sacks (Quintal)', nameAmharic: 'የእህል ኩንታል', productCount: 24 },
      { id: 'sub-farming-tools', name: 'Farming Equipment', nameAmharic: 'የእርሻ መገልገያዎች', productCount: 28 },
    ],
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-teff-magna',
    name: 'Premium Magna White Teff (25kg Bag)',
    nameAmharic: 'የተመረጠ ነጭ ማኛ ጤፍ (25 ኪ.ግ)',
    description: 'Authentic high-plateau Magna Teff sourced directly from verified farmer unions in East Gojjam and Gondar. Cleaned, destoned, and packaged fresh for traditional injera making with guaranteed spongy texture and golden color.',
    price: 3650,
    oldPrice: 4200,
    discountPercentage: 13,
    rating: 4.9,
    reviewCount: 168,
    soldCount: 840,
    images: [
      'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
    ],
    categoryId: 'cat-groceries',
    categoryName: 'Groceries & Foods',
    subcategoryId: 'sub-teff-grains',
    subcategoryName: 'Teff & Grains',
    seller: {
      id: 'sell-gondar-union',
      name: 'Gondar Farmers Agricultural Union',
      verified: true,
      rating: 4.9,
      salesCount: 2150,
      city: 'Gondar',
      responseRate: '98%',
    },
    stock: 45,
    unit: '25kg',
    isFlashDeal: true,
    isPopular: true,
    isRecommended: true,
    origin: 'East Gojjam / Gondar',
    attributes: {
      'Grade': ['Grade 1 Magna', 'Sergegna Mixed'],
      'Packaging': ['25kg Sack', '50kg Sack', '100kg Quintal'],
    },
  },
  {
    id: 'prod-yirgacheffe-coffee',
    name: 'Yirgacheffe Grade 1 Specialty Coffee Beans (1kg)',
    nameAmharic: 'ይርጋጨፌ አንደኛ ደረጃ የቡና ፍሬ (1 ኪ.ግ)',
    description: 'Single-origin washed Arabica coffee beans from the mist-covered highlands of Yirgacheffe. Renowned worldwide for floral jasmine aromas, bright citrus notes, and a clean caramel finish.',
    price: 950,
    oldPrice: 1150,
    discountPercentage: 17,
    rating: 4.9,
    reviewCount: 230,
    soldCount: 1250,
    images: [
      'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    ],
    categoryId: 'cat-groceries',
    categoryName: 'Groceries & Foods',
    subcategoryId: 'sub-coffee-tea',
    subcategoryName: 'Ethiopian Coffee & Tea',
    seller: {
      id: 'sell-sidama-roasters',
      name: 'Sheba Heritage Coffee Exporters',
      verified: true,
      rating: 5.0,
      salesCount: 3400,
      city: 'Addis Ababa',
      responseRate: '100%',
    },
    stock: 120,
    unit: '1kg',
    isFlashDeal: true,
    isPopular: true,
    isRecommended: true,
    origin: 'Yirgacheffe, Gedeo',
    attributes: {
      'Roast Level': ['Green (Raw Beans)', 'Medium Roast', 'Dark Roast'],
      'Form': ['Whole Beans', 'Fresh Ground'],
    },
  },
  {
    id: 'prod-habesha-kemis',
    name: 'Handwoven Sheba Traditional Habesha Kemis with Netela',
    nameAmharic: 'በእጅ የተሸመነ የሐበሻ ቀሚስ ከነጠላ ጋር',
    description: 'Masterfully handwoven from 100% pure Ethiopian cotton (Shemane craft). Features intricate Tilf and Tibeb embroidery along the neckline, sleeves, and hemline. Comes with a matching lightweight Netela.',
    price: 6800,
    oldPrice: 8500,
    discountPercentage: 20,
    rating: 4.8,
    reviewCount: 94,
    soldCount: 310,
    images: [
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80',
    ],
    categoryId: 'cat-fashion',
    categoryName: 'Traditional & Fashion',
    subcategoryId: 'sub-habesha-kemis',
    subcategoryName: 'Habesha Kemis',
    seller: {
      id: 'sell-tibeb-shiraf',
      name: 'Tibeb & Shemane Collective',
      verified: true,
      rating: 4.8,
      salesCount: 940,
      city: 'Addis Ababa',
      responseRate: '95%',
    },
    stock: 15,
    unit: 'Full Set',
    isFlashDeal: false,
    isPopular: true,
    isRecommended: true,
    origin: 'Shiro Meda, Addis Ababa',
    attributes: {
      'Size': ['Small (S)', 'Medium (M)', 'Large (L)', 'Custom Fit'],
      'Tibeb Pattern': ['Golden Royal', 'Emerald Green', 'Heritage Cross'],
    },
  },
  {
    id: 'prod-berbere-special',
    name: 'Gondar Heritage Traditional Berbere Blend (1kg)',
    nameAmharic: 'የጎንደር ባህላዊ የተደባለቀ በርበሬ (1 ኪ.ግ)',
    description: 'Made according to heirloom recipes with sundried Mareko Fana peppers, garlic, ginger, rue, korarima (false cardamom), and holy basil. Rich burgundy color with deep aromatic warmth for Doro Wat and stewing.',
    price: 520,
    oldPrice: 620,
    discountPercentage: 16,
    rating: 4.9,
    reviewCount: 312,
    soldCount: 1840,
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=600&q=80',
    ],
    categoryId: 'cat-groceries',
    categoryName: 'Groceries & Foods',
    subcategoryId: 'sub-spices',
    subcategoryName: 'Spices & Berbere',
    seller: {
      id: 'sell-fana-spices',
      name: 'Ardab Verified Organics',
      verified: true,
      rating: 4.9,
      salesCount: 4200,
      city: 'Gondar',
      responseRate: '99%',
    },
    stock: 85,
    unit: '1kg',
    isFlashDeal: true,
    isPopular: true,
    isRecommended: false,
    origin: 'Gondar',
    attributes: {
      'Heat Level': ['Medium Spicy', 'Extra Spicy', 'Mild Blend'],
    },
  },
  {
    id: 'prod-electric-mitad',
    name: 'Automatic Energy-Saving Electric Injera Mitad 60cm',
    nameAmharic: 'የኤሌክትሪክ የኢንጀራ ምጣድ 60 ሳ.ሜ',
    description: 'Durable non-stick polished clay-ceramic surface with advanced dual-spiral heating element. Consumes 30% less electricity, heats uniformly across the whole diameter, and comes with high heat safety insulation.',
    price: 7400,
    oldPrice: 8200,
    discountPercentage: 10,
    rating: 4.7,
    reviewCount: 78,
    soldCount: 220,
    images: [
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80',
    ],
    categoryId: 'cat-home-kitchen',
    categoryName: 'Home & Kitchen',
    subcategoryId: 'sub-mitad-appliances',
    subcategoryName: 'Electric Mitad & Stoves',
    seller: {
      id: 'sell-alembirhan',
      name: 'Alem Birhan Appliances',
      verified: true,
      rating: 4.6,
      salesCount: 650,
      city: 'Addis Ababa',
      responseRate: '92%',
    },
    stock: 22,
    unit: 'Piece',
    isFlashDeal: false,
    isPopular: true,
    isRecommended: true,
    origin: 'Addis Ababa Assembly',
    attributes: {
      'Plate Diameter': ['55 cm Standard', '60 cm Large'],
      'Voltage': ['220V Heavy Duty'],
    },
  },
  {
    id: 'prod-solar-powerbank',
    name: 'Heavy Duty 30000mAh Solar Power Bank with Triple LED Lamp',
    nameAmharic: 'ባለ 30000mAh ሶላር ፓወር ባንክ ከኤልኢዲ መብራት ጋር',
    description: 'Rugged water-resistant portable power station with high-efficiency monocrystalline solar charging panel, fast 22.5W USB-C PD delivery, and ultra-bright floodlight lamp ideal for travel and power cuts.',
    price: 2450,
    oldPrice: 3100,
    discountPercentage: 21,
    rating: 4.8,
    reviewCount: 142,
    soldCount: 670,
    images: [
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=600&q=80',
    ],
    categoryId: 'cat-electronics',
    categoryName: 'Electronics & Power',
    subcategoryId: 'sub-solar-power',
    subcategoryName: 'Solar & Power Banks',
    seller: {
      id: 'sell-tekno-ethiopia',
      name: 'Tekno Smart Solutions',
      verified: true,
      rating: 4.8,
      salesCount: 1890,
      city: 'Hawassa',
      responseRate: '97%',
    },
    stock: 60,
    unit: 'Unit',
    isFlashDeal: true,
    isPopular: true,
    isRecommended: true,
    origin: 'Imported Verified',
    attributes: {
      'Color': ['Matte Black', 'Army Green', 'Rescue Orange'],
    },
  },
  {
    id: 'prod-tigray-honey',
    name: 'Pure Raw White Honey from Lalibela & Tigray Highlands (1kg)',
    nameAmharic: 'የላሊበላ እና ትግራይ የተፈጥሮ ነጭ ማር (1 ኪ.ግ)',
    description: 'Unprocessed, 100% natural white honey harvested from wild acacia blossoms in high mountain forests. Naturally thick, creamy texture with gentle floral sweetness and rich medicinal antioxidants.',
    price: 850,
    oldPrice: 1000,
    discountPercentage: 15,
    rating: 5.0,
    reviewCount: 198,
    soldCount: 920,
    images: [
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1471943311424-646960669fbc?auto=format&fit=crop&w=600&q=80',
    ],
    categoryId: 'cat-groceries',
    categoryName: 'Groceries & Foods',
    subcategoryId: 'sub-oil-honey',
    subcategoryName: 'Honey & Oils',
    seller: {
      id: 'sell-fana-spices',
      name: 'Ardab Verified Organics',
      verified: true,
      rating: 4.9,
      salesCount: 4200,
      city: 'Gondar',
      responseRate: '99%',
    },
    stock: 40,
    unit: '1kg Glass Jar',
    isFlashDeal: false,
    isPopular: true,
    isRecommended: true,
    origin: 'Lalibela / Tigray',
  },
  {
    id: 'prod-jebena-set',
    name: 'Traditional Handcrafted Clay Jebena & 6 Sini Cup Set',
    nameAmharic: 'ባህላዊ የሸክላ ጀበና እና 6 የሲኒ ስብስብ',
    description: 'Authentic handmade Ethiopian clay coffee pot with woven straw base (Matat) and 6 matching porcelain Sini cups featuring classic Ethiopian cross motifs.',
    price: 1350,
    oldPrice: 1600,
    discountPercentage: 15,
    rating: 4.7,
    reviewCount: 65,
    soldCount: 390,
    images: [
      'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    ],
    categoryId: 'cat-home-kitchen',
    categoryName: 'Home & Kitchen',
    subcategoryId: 'sub-coffee-sets',
    subcategoryName: 'Jebena & Sini Sets',
    seller: {
      id: 'sell-tibeb-shiraf',
      name: 'Tibeb & Shemane Collective',
      verified: true,
      rating: 4.8,
      salesCount: 940,
      city: 'Addis Ababa',
      responseRate: '95%',
    },
    stock: 25,
    unit: 'Set',
    isFlashDeal: false,
    isPopular: false,
    isRecommended: true,
    origin: 'Addis Ababa',
  },
];

export const MOCK_USER: UserProfile = {
  id: 'usr-customer-001',
  fullName: 'Yonas Tadesse',
  email: 'yonas.tadesse@example.com',
  phone: '+251 91 123 4567',
  city: 'Gondar',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  verified: true,
  joinedDate: 'January 2025',
};

export const MOCK_ADDRESSES = [
  {
    id: 'addr-01',
    fullName: 'Yonas Tadesse',
    phone: '+251 91 123 4567',
    city: 'Gondar',
    subcity: 'Maraki',
    woreda: 'Kebele 16',
    specificAddress: 'Near University of Gondar, Maraki Campus Gate 2',
    isDefault: true,
  },
  {
    id: 'addr-02',
    fullName: 'Yonas Tadesse (Office)',
    phone: '+251 92 888 9900',
    city: 'Gondar',
    subcity: 'Piazza',
    woreda: 'Kebele 02',
    specificAddress: 'Commercial Bank of Ethiopia Main Branch Building, 3rd Floor',
    isDefault: false,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-10293',
    orderNumber: 'ARD-2026-9042',
    createdAt: '2026-09-22T14:30:00Z',
    status: 'SHIPPING',
    items: [
      {
        product: MOCK_PRODUCTS[0], // Teff Magna
        quantity: 1,
        price: 3650,
      },
      {
        product: MOCK_PRODUCTS[3], // Berbere
        quantity: 2,
        price: 520,
      },
    ],
    subtotal: 4690,
    deliveryFee: 150,
    discount: 0,
    total: 4840,
    shippingAddress: MOCK_ADDRESSES[0],
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'PENDING',
    estimatedDelivery: 'Tomorrow by 4:00 PM',
    trackingSteps: [
      {
        title: 'Order Confirmed',
        description: 'Seller received and verified your order',
        timestamp: 'Sep 22, 2:32 PM',
        completed: true,
        current: false,
      },
      {
        title: 'Packed & Dispatched',
        description: 'Packed at Gondar Regional Distribution Hub',
        timestamp: 'Sep 23, 9:15 AM',
        completed: true,
        current: false,
      },
      {
        title: 'In Transit / With Courier',
        description: 'Ardab Delivery Agent Abebe is en route to Maraki',
        timestamp: 'Sep 24, 8:40 AM',
        completed: false,
        current: true,
      },
      {
        title: 'Delivered',
        description: 'Package handed over to customer',
        completed: false,
        current: false,
      },
    ],
  },
  {
    id: 'ord-10188',
    orderNumber: 'ARD-2026-8140',
    createdAt: '2026-09-15T10:12:00Z',
    status: 'DELIVERED',
    items: [
      {
        product: MOCK_PRODUCTS[1], // Yirgacheffe Coffee
        quantity: 2,
        price: 950,
      },
    ],
    subtotal: 1900,
    deliveryFee: 120,
    discount: 100,
    total: 1920,
    shippingAddress: MOCK_ADDRESSES[0],
    paymentMethod: 'Telebirr',
    paymentStatus: 'PAID',
    estimatedDelivery: 'Delivered Sep 17',
    trackingSteps: [
      {
        title: 'Order Placed',
        description: 'Paid with Telebirr',
        timestamp: 'Sep 15, 10:12 AM',
        completed: true,
        current: false,
      },
      {
        title: 'Processed & Shipped',
        description: 'Dispatched from Addis Ababa Central Depot',
        timestamp: 'Sep 16, 11:00 AM',
        completed: true,
        current: false,
      },
      {
        title: 'Delivered',
        description: 'Signed and received by Yonas Tadesse',
        timestamp: 'Sep 17, 3:20 PM',
        completed: true,
        current: false,
      },
    ],
  },
  {
    id: 'ord-10050',
    orderNumber: 'ARD-2026-7201',
    createdAt: '2026-09-02T16:00:00Z',
    status: 'DELIVERED',
    items: [
      {
        product: MOCK_PRODUCTS[6], // Tigray Honey
        quantity: 1,
        price: 850,
      },
    ],
    subtotal: 850,
    deliveryFee: 100,
    discount: 0,
    total: 950,
    shippingAddress: MOCK_ADDRESSES[0],
    paymentMethod: 'CBE Birr',
    paymentStatus: 'PAID',
    estimatedDelivery: 'Delivered Sep 04',
    trackingSteps: [
      {
        title: 'Delivered',
        description: 'Successfully delivered',
        timestamp: 'Sep 04, 1:45 PM',
        completed: true,
        current: false,
      },
    ],
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Your Order is on the Way!',
    body: 'Order #ARD-2026-9042 is out for delivery with our courier in Gondar.',
    createdAt: '10 minutes ago',
    read: false,
    type: 'order',
  },
  {
    id: 'notif-2',
    title: 'New Harvest Teff Magna Arrived',
    body: 'Fresh East Gojjam Magna Teff is now available at special wholesale rates.',
    createdAt: '2 hours ago',
    read: false,
    type: 'promo',
  },
  {
    id: 'notif-3',
    title: 'Profile Verified',
    body: 'Your Ardab Market customer identity has been verified.',
    createdAt: '3 days ago',
    read: true,
    type: 'security',
  },
];

export const MOCK_PROMO_BANNERS = [
  {
    id: 'banner-1',
    title: 'Ethiopian New Year Super Harvest Sale',
    subtitle: 'Up to 25% OFF on Pure Teff & Yirgacheffe Coffee',
    buttonText: 'Shop Harvest Deals',
    badge: 'Limited Time Deal',
    bgGradient: ['#145A46', '#0E4032'],
    accentColor: '#7ED321',
  },
  {
    id: 'banner-2',
    title: 'Authentic Sheba Handwoven Kemis',
    subtitle: 'Pure cotton crafted by master artisans in Shiro Meda',
    buttonText: 'Explore Fashion',
    badge: 'Verified Merchants',
    bgGradient: ['#0E4032', '#1B6A53'],
    accentColor: '#FFB300',
  },
  {
    id: 'banner-3',
    title: 'Fast & Secure Gondar City Delivery',
    subtitle: 'Delivery to your door in 24 hours or less',
    buttonText: 'Browse Local Goods',
    badge: 'Express Delivery',
    bgGradient: ['#164E3D', '#0B3327'],
    accentColor: '#7ED321',
  },
];

export const MOCK_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: 'tick-01',
    ticketNumber: 'TKT-8831',
    subject: 'Inquiry regarding 50kg Teff delivery time to Maraki',
    category: 'Delivery Question',
    status: 'IN_PROGRESS',
    lastUpdated: '1 hour ago',
    messages: [
      {
        id: 'msg-1',
        sender: 'customer',
        text: 'Hello, I ordered a 25kg sack of Teff. Will the driver call before arriving at Maraki Campus Gate 2?',
        timestamp: 'Sep 23, 11:20 AM',
      },
      {
        id: 'msg-2',
        sender: 'support',
        text: 'Greetings Yonas! Yes, our driver Abebe will call you approximately 20-30 minutes prior to delivery. You can also track the driver directly on the app tracking screen.',
        timestamp: 'Sep 23, 11:45 AM',
      },
    ],
  },
];
