// ==============================================================================
// Ardab Market - Customer Mobile Auth Response Codes
// ==============================================================================
// Standard machine-readable codes consumed by React Native client localization.

export const AuthResponseCode = {
  // Success
  SUCCESS: 'SUCCESS',
  OTP_SENT: 'OTP_SENT',
  OTP_VERIFIED: 'OTP_VERIFIED',
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  SESSION_REFRESHED: 'SESSION_REFRESHED',
  LOGGED_OUT: 'LOGGED_OUT',
  PASSWORD_RESET_SENT: 'PASSWORD_RESET_SENT',
  PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',

  // Validation & Input
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PHONE: 'INVALID_PHONE',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',

  // Conflict / Uniqueness
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  TELEGRAM_ALREADY_EXISTS: 'TELEGRAM_ALREADY_EXISTS',

  // OTP & Verification
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  REGISTRATION_EXPIRED: 'REGISTRATION_EXPIRED',
  TELEGRAM_SERVICE_UNAVAILABLE: 'TELEGRAM_SERVICE_UNAVAILABLE',

  // Credentials & Account
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCOUNT_NOT_VERIFIED: 'ACCOUNT_NOT_VERIFIED',

  // Session & Security
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  SESSION_REVOKED: 'SESSION_REVOKED',
};
