/**
 * Ardab Market — Notifications & Operational Alerts Constants
 */

export const NOTIFICATION_TYPES = {
  NOTIFICATION: 'NOTIFICATION',
  OPERATIONAL_ALERT: 'OPERATIONAL_ALERT',
  SYSTEM_ANNOUNCEMENT: 'SYSTEM_ANNOUNCEMENT',
};

export const NOTIFICATION_CATEGORIES = {
  ORDER: 'ORDER',
  DELIVERY: 'DELIVERY',
  FLEET: 'FLEET',
  SECURITY: 'SECURITY',
  SYSTEM: 'SYSTEM',
  PAYMENT: 'PAYMENT',
  CUSTOMER: 'CUSTOMER',
};

export const NOTIFICATION_SEVERITIES = {
  INFO: 'INFO',
  SUCCESS: 'SUCCESS',
  WARNING: 'WARNING',
  CRITICAL: 'CRITICAL',
};

export const NOTIFICATION_PRIORITIES = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};
