// ==============================================================================
// Ardab Market - Customer Support Constants & Enums
// ==============================================================================

export const SUPPORT_TICKET_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_FOR_CUSTOMER: 'WAITING_FOR_CUSTOMER',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
};

export const SUPPORT_TICKET_PRIORITY = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};

export const SUPPORT_SENDER_TYPE = {
  CUSTOMER: 'CUSTOMER',
  SUBADMIN: 'SUBADMIN',
  SYSTEM: 'SYSTEM',
};

export const SUPPORT_MESSAGE_TYPE = {
  MESSAGE: 'MESSAGE',
  INTERNAL_NOTE: 'INTERNAL_NOTE',
  SYSTEM_EVENT: 'SYSTEM_EVENT',
};

export const SUPPORT_EMAIL_STATUS = {
  QUEUED: 'QUEUED',
  SENDING: 'SENDING',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
};

export const DEFAULT_SUPPORT_CATEGORIES = [
  'ORDER',
  'DELIVERY',
  'PAYMENT',
  'ACCOUNT',
  'PRODUCT',
  'SELLER',
  'REFUND',
  'TECHNICAL',
  'OTHER',
];

export const VALID_STATUS_TRANSITIONS = {
  [SUPPORT_TICKET_STATUS.OPEN]: [
    SUPPORT_TICKET_STATUS.IN_PROGRESS,
    SUPPORT_TICKET_STATUS.WAITING_FOR_CUSTOMER,
    SUPPORT_TICKET_STATUS.RESOLVED,
    SUPPORT_TICKET_STATUS.CLOSED,
  ],
  [SUPPORT_TICKET_STATUS.IN_PROGRESS]: [
    SUPPORT_TICKET_STATUS.WAITING_FOR_CUSTOMER,
    SUPPORT_TICKET_STATUS.RESOLVED,
    SUPPORT_TICKET_STATUS.CLOSED,
    SUPPORT_TICKET_STATUS.OPEN,
  ],
  [SUPPORT_TICKET_STATUS.WAITING_FOR_CUSTOMER]: [
    SUPPORT_TICKET_STATUS.IN_PROGRESS,
    SUPPORT_TICKET_STATUS.RESOLVED,
    SUPPORT_TICKET_STATUS.CLOSED,
  ],
  [SUPPORT_TICKET_STATUS.RESOLVED]: [
    SUPPORT_TICKET_STATUS.CLOSED,
    SUPPORT_TICKET_STATUS.IN_PROGRESS, // Reopened
  ],
  [SUPPORT_TICKET_STATUS.CLOSED]: [
    SUPPORT_TICKET_STATUS.OPEN, // Reopened
  ],
};
